-- ============================================================================================
-- migrations/cp/0007_seed.sql              database: aibuilder-cp
--
-- Keys MUST stay in sync with packages/core/src/industries.ts (single source of truth).
--
-- PURPOSE
--   Reference data. Locales, the two-level industry taxonomy, and the reserved-slug list that
--   the triggers in 0006 enforce. Nothing here is tenant data, so this file is re-runnable in
--   spirit: every statement is an idempotent upsert on the natural key, which matters because a
--   seed that cannot be re-applied is a seed that drifts from the code that mirrors it.
--
--   Adding a seventh locale is one INSERT here plus one entry in packages/core/src/locales.ts.
--   Adding an industry is one INSERT here plus one entry in packages/core/src/industries.ts.
--   Neither is a schema change, which is the whole point of the taxonomy tables.
--
-- MIGRATION RULE (architecture §5.4). A cascade-parent table can NEVER be rebuilt in place on
--   D1: `PRAGMA foreign_keys=OFF` is unsupported and `defer_foreign_keys` defers constraint
--   *checking*, not FK *actions*, so a 12-step rebuild cascade-deletes every child row while
--   `foreign_key_check` still passes. Expand -> migrate -> contract with `ALTER TABLE
--   ADD/DROP/RENAME COLUMN` only. `locales`, `industry_groups` and `industries` are all cascade
--   parents; changing one of their CHECK constraints means a new table, never a rebuild.
--
-- TRANSLATIONS
--   `industry_groups.labels` carries all six locales inline (see the column comment in 0002).
--   `industry_translations` is seeded for nl and en only: Dutch is the primary UI language and
--   English is the fallback the bootstrap route serves when a locale has no row. de/fr/es/pt
--   labels land with their locale rollout in Phase 2 as pure INSERTs, no migration.
-- ============================================================================================

INSERT INTO locales (code, english_name, native_name, hreflang, url_segment, direction, is_active, sort_order, created_at) VALUES
  ('nl', 'Dutch', 'Nederlands', 'nl', 'nl', 'ltr', 1, 10, unixepoch() * 1000),
  ('en', 'English', 'English', 'en', 'en', 'ltr', 1, 20, unixepoch() * 1000),
  ('de', 'German', 'Deutsch', 'de', 'de', 'ltr', 1, 30, unixepoch() * 1000),
  ('fr', 'French', 'Français', 'fr', 'fr', 'ltr', 1, 40, unixepoch() * 1000),
  ('es', 'Spanish', 'Español', 'es', 'es', 'ltr', 1, 50, unixepoch() * 1000),
  ('pt', 'Portuguese', 'Português', 'pt', 'pt', 'ltr', 1, 60, unixepoch() * 1000)
ON CONFLICT(code) DO UPDATE SET
  english_name = excluded.english_name,
  native_name  = excluded.native_name,
  hreflang     = excluded.hreflang,
  url_segment  = excluded.url_segment,
  sort_order   = excluded.sort_order;

-- >>> GENERATED TAXONOMY — do not edit by hand; run `pnpm seed:taxonomy`. >>>
--
-- Projected from packages/core/src/industries.ts by scripts/generate-taxonomy-seed.mjs.
-- 14 groups, 104 industries, 624 translations.
--
-- `additional_type` carries the meaning `schema_org_type` had to drop when no LocalBusiness
-- subtype fits; `design_preset` is NULL everywhere in Phase 1, which means "take the archetype's
-- own knob defaults" from packages/site-kit/src/tokens/dna.ts.
--
-- `stock_query` is NULL by design: Phase 1 sources hero photography from the per-GROUP pool in
-- apps/generator/src/steps/media.ts (CURATED_STOCK_QUERIES), which is scene-written and
-- deliberately gives two businesses in one trade different heroes. A per-industry override here
-- is an UPDATE when one is worth writing, never a migration.

INSERT INTO industry_groups (key, icon, labels, is_active, sort_order, created_at) VALUES
  ('food_drink', 'utensils', '{"nl":"Eten & drinken","en":"Food & drink","de":"Essen & Trinken","fr":"Restauration","es":"Comida y bebida","pt":"Comida e bebida"}', 1, 10, unixepoch() * 1000),
  ('beauty', 'scissors', '{"nl":"Schoonheid & verzorging","en":"Beauty & personal care","de":"Beauty & Pflege","fr":"Beauté & soins","es":"Belleza y cuidado personal","pt":"Beleza e cuidados pessoais"}', 1, 20, unixepoch() * 1000),
  ('health', 'stethoscope', '{"nl":"Gezondheid & zorg","en":"Health & medical","de":"Gesundheit & Medizin","fr":"Santé & médical","es":"Salud y medicina","pt":"Saúde e medicina"}', 1, 30, unixepoch() * 1000),
  ('sport', 'dumbbell', '{"nl":"Sport & fitness","en":"Sport & fitness","de":"Sport & Fitness","fr":"Sport & fitness","es":"Deporte y fitness","pt":"Desporto e fitness"}', 1, 40, unixepoch() * 1000),
  ('trades', 'wrench', '{"nl":"Bouw & installatie","en":"Home & trades","de":"Bau & Handwerk","fr":"Bâtiment & artisanat","es":"Construcción y oficios","pt":"Construção e ofícios"}', 1, 50, unixepoch() * 1000),
  ('automotive', 'car', '{"nl":"Auto & vervoer","en":"Automotive & transport","de":"Auto & Verkehr","fr":"Auto & transport","es":"Automoción y transporte","pt":"Automóvel e transporte"}', 1, 60, unixepoch() * 1000),
  ('retail', 'shopping-bag', '{"nl":"Winkels","en":"Retail","de":"Einzelhandel","fr":"Commerce de détail","es":"Comercio","pt":"Comércio"}', 1, 70, unixepoch() * 1000),
  ('professional', 'briefcase', '{"nl":"Zakelijke diensten","en":"Professional services","de":"Dienstleistungen","fr":"Services professionnels","es":"Servicios profesionales","pt":"Serviços profissionais"}', 1, 80, unixepoch() * 1000),
  ('events', 'music', '{"nl":"Events & entertainment","en":"Events & entertainment","de":"Events & Entertainment","fr":"Événements & spectacle","es":"Eventos y entretenimiento","pt":"Eventos e entretenimento"}', 1, 90, unixepoch() * 1000),
  ('education', 'graduation-cap', '{"nl":"Onderwijs","en":"Education & training","de":"Bildung & Weiterbildung","fr":"Éducation & formation","es":"Educación y formación","pt":"Educação e formação"}', 1, 100, unixepoch() * 1000),
  ('real_estate', 'building', '{"nl":"Vastgoed","en":"Real estate","de":"Immobilien","fr":"Immobilier","es":"Inmobiliaria","pt":"Imobiliário"}', 1, 110, unixepoch() * 1000),
  ('travel', 'bed', '{"nl":"Reizen & verblijf","en":"Travel & hospitality","de":"Reisen & Übernachten","fr":"Voyage & hébergement","es":"Viajes y alojamiento","pt":"Viagens e alojamento"}', 1, 120, unixepoch() * 1000),
  ('pets', 'paw', '{"nl":"Huisdieren","en":"Pets & animals","de":"Haustiere","fr":"Animaux","es":"Mascotas","pt":"Animais"}', 1, 130, unixepoch() * 1000),
  ('crafts', 'hammer', '{"nl":"Ambacht & overig","en":"Craft, services & other","de":"Handwerk & Sonstiges","fr":"Artisanat & autres","es":"Artesanía y otros","pt":"Artesanato e outros"}', 1, 140, unixepoch() * 1000)
ON CONFLICT(key) DO UPDATE SET
  icon = excluded.icon, labels = excluded.labels, sort_order = excluded.sort_order;

INSERT INTO industries (key, group_key, schema_org_type, dna_id, additional_type, stock_query, is_active, sort_order, created_at) VALUES
  ('restaurant', 'food_drink', 'Restaurant', 'warm_trattoria', NULL, NULL, 1, 10, unixepoch() * 1000),
  ('cafe', 'food_drink', 'CafeOrCoffeeShop', 'warm_trattoria', NULL, NULL, 1, 20, unixepoch() * 1000),
  ('bakery', 'food_drink', 'Bakery', 'warm_trattoria', NULL, NULL, 1, 30, unixepoch() * 1000),
  ('bar_pub', 'food_drink', 'BarOrPub', 'midnight_neon', NULL, NULL, 1, 40, unixepoch() * 1000),
  ('takeaway', 'food_drink', 'FastFoodRestaurant', 'warm_trattoria', NULL, NULL, 1, 50, unixepoch() * 1000),
  ('food_truck', 'food_drink', 'FoodEstablishment', 'warm_trattoria', NULL, NULL, 1, 60, unixepoch() * 1000),
  ('ice_cream', 'food_drink', 'IceCreamShop', 'warm_trattoria', NULL, NULL, 1, 70, unixepoch() * 1000),
  ('catering', 'food_drink', 'FoodEstablishment', 'warm_trattoria', NULL, NULL, 1, 80, unixepoch() * 1000),
  ('brewery', 'food_drink', 'Brewery', 'garage_steel', NULL, NULL, 1, 90, unixepoch() * 1000),
  ('hairdresser', 'beauty', 'HairSalon', 'warm_trattoria', NULL, NULL, 1, 100, unixepoch() * 1000),
  ('barbershop', 'beauty', 'HairSalon', 'midnight_neon', NULL, NULL, 1, 110, unixepoch() * 1000),
  ('beauty_salon', 'beauty', 'BeautySalon', 'warm_trattoria', NULL, NULL, 1, 120, unixepoch() * 1000),
  ('nail_studio', 'beauty', 'NailSalon', 'warm_trattoria', NULL, NULL, 1, 130, unixepoch() * 1000),
  ('day_spa', 'beauty', 'DaySpa', 'clinical_trust', NULL, NULL, 1, 140, unixepoch() * 1000),
  ('massage', 'beauty', 'HealthAndBeautyBusiness', 'clinical_trust', NULL, NULL, 1, 150, unixepoch() * 1000),
  ('tattoo_studio', 'beauty', 'TattooParlor', 'midnight_neon', NULL, NULL, 1, 160, unixepoch() * 1000),
  ('gp_practice', 'health', 'Physician', 'clinical_trust', NULL, NULL, 1, 170, unixepoch() * 1000),
  ('dentist', 'health', 'Dentist', 'clinical_trust', NULL, NULL, 1, 180, unixepoch() * 1000),
  ('physiotherapist', 'health', 'Physiotherapy', 'clinical_trust', NULL, NULL, 1, 190, unixepoch() * 1000),
  ('chiropractor', 'health', 'MedicalBusiness', 'clinical_trust', NULL, NULL, 1, 200, unixepoch() * 1000),
  ('psychologist', 'health', 'MedicalBusiness', 'clinical_trust', NULL, NULL, 1, 210, unixepoch() * 1000),
  ('optician', 'health', 'Optician', 'clinical_trust', NULL, NULL, 1, 220, unixepoch() * 1000),
  ('pharmacy', 'health', 'Pharmacy', 'clinical_trust', NULL, NULL, 1, 230, unixepoch() * 1000),
  ('home_care', 'health', 'MedicalBusiness', 'clinical_trust', NULL, NULL, 1, 240, unixepoch() * 1000),
  ('gym', 'sport', 'ExerciseGym', 'midnight_neon', NULL, NULL, 1, 250, unixepoch() * 1000),
  ('crossfit_box', 'sport', 'ExerciseGym', 'midnight_neon', NULL, NULL, 1, 260, unixepoch() * 1000),
  ('yoga_studio', 'sport', 'SportsActivityLocation', 'clinical_trust', NULL, NULL, 1, 270, unixepoch() * 1000),
  ('personal_trainer', 'sport', 'SportsActivityLocation', 'midnight_neon', NULL, NULL, 1, 280, unixepoch() * 1000),
  ('martial_arts', 'sport', 'SportsClub', 'midnight_neon', NULL, NULL, 1, 290, unixepoch() * 1000),
  ('dance_school', 'sport', 'SportsActivityLocation', 'warm_trattoria', NULL, NULL, 1, 300, unixepoch() * 1000),
  ('racket_club', 'sport', 'TennisComplex', 'clinical_trust', NULL, NULL, 1, 310, unixepoch() * 1000),
  ('plumber', 'trades', 'Plumber', 'garage_steel', NULL, NULL, 1, 320, unixepoch() * 1000),
  ('electrician', 'trades', 'Electrician', 'garage_steel', NULL, NULL, 1, 330, unixepoch() * 1000),
  ('hvac_heatpump', 'trades', 'HVACBusiness', 'garage_steel', NULL, NULL, 1, 340, unixepoch() * 1000),
  ('general_contractor', 'trades', 'GeneralContractor', 'garage_steel', NULL, NULL, 1, 350, unixepoch() * 1000),
  ('painter_decorator', 'trades', 'HousePainter', 'garage_steel', NULL, NULL, 1, 360, unixepoch() * 1000),
  ('roofer', 'trades', 'RoofingContractor', 'garage_steel', NULL, NULL, 1, 370, unixepoch() * 1000),
  ('carpenter', 'trades', 'HomeAndConstructionBusiness', 'garage_steel', NULL, NULL, 1, 380, unixepoch() * 1000),
  ('locksmith', 'trades', 'Locksmith', 'garage_steel', NULL, NULL, 1, 390, unixepoch() * 1000),
  ('landscaper', 'trades', 'HomeAndConstructionBusiness', 'garage_steel', NULL, NULL, 1, 400, unixepoch() * 1000),
  ('solar_installer', 'trades', 'HomeAndConstructionBusiness', 'garage_steel', NULL, NULL, 1, 410, unixepoch() * 1000),
  ('car_repair', 'automotive', 'AutoRepair', 'garage_steel', NULL, NULL, 1, 420, unixepoch() * 1000),
  ('car_dealer', 'automotive', 'AutoDealer', 'clinical_trust', NULL, NULL, 1, 430, unixepoch() * 1000),
  ('car_bodywork', 'automotive', 'AutoBodyShop', 'garage_steel', NULL, NULL, 1, 440, unixepoch() * 1000),
  ('tyre_service', 'automotive', 'TireStore', 'garage_steel', NULL, NULL, 1, 450, unixepoch() * 1000),
  ('car_wash', 'automotive', 'AutoWash', 'clinical_trust', NULL, NULL, 1, 460, unixepoch() * 1000),
  ('bike_shop', 'automotive', 'BikeStore', 'garage_steel', NULL, NULL, 1, 470, unixepoch() * 1000),
  ('driving_school', 'automotive', 'AutomotiveBusiness', 'midnight_neon', 'https://www.wikidata.org/wiki/Q2143665', NULL, 1, 480, unixepoch() * 1000),
  ('clothing_store', 'retail', 'ClothingStore', 'warm_trattoria', NULL, NULL, 1, 490, unixepoch() * 1000),
  ('shoe_store', 'retail', 'ShoeStore', 'warm_trattoria', NULL, NULL, 1, 500, unixepoch() * 1000),
  ('jeweller', 'retail', 'JewelryStore', 'warm_trattoria', NULL, NULL, 1, 510, unixepoch() * 1000),
  ('florist', 'retail', 'Florist', 'clinical_trust', NULL, NULL, 1, 520, unixepoch() * 1000),
  ('bookshop', 'retail', 'BookStore', 'warm_trattoria', NULL, NULL, 1, 530, unixepoch() * 1000),
  ('toy_store', 'retail', 'ToyStore', 'warm_trattoria', NULL, NULL, 1, 540, unixepoch() * 1000),
  ('furniture_store', 'retail', 'FurnitureStore', 'clinical_trust', NULL, NULL, 1, 550, unixepoch() * 1000),
  ('electronics_store', 'retail', 'ElectronicsStore', 'midnight_neon', NULL, NULL, 1, 560, unixepoch() * 1000),
  ('sports_store', 'retail', 'SportingGoodsStore', 'midnight_neon', NULL, NULL, 1, 570, unixepoch() * 1000),
  ('pet_store', 'retail', 'PetStore', 'clinical_trust', NULL, NULL, 1, 580, unixepoch() * 1000),
  ('butcher', 'retail', 'Store', 'warm_trattoria', 'https://www.wikidata.org/wiki/Q329737', NULL, 1, 590, unixepoch() * 1000),
  ('farm_shop', 'retail', 'GroceryStore', 'warm_trattoria', NULL, NULL, 1, 600, unixepoch() * 1000),
  ('accountant', 'professional', 'AccountingService', 'clinical_trust', NULL, NULL, 1, 610, unixepoch() * 1000),
  ('lawyer', 'professional', 'Attorney', 'clinical_trust', NULL, NULL, 1, 620, unixepoch() * 1000),
  ('notary', 'professional', 'Notary', 'clinical_trust', NULL, NULL, 1, 630, unixepoch() * 1000),
  ('tax_adviser', 'professional', 'AccountingService', 'clinical_trust', NULL, NULL, 1, 640, unixepoch() * 1000),
  ('insurance_broker', 'professional', 'InsuranceAgency', 'clinical_trust', NULL, NULL, 1, 650, unixepoch() * 1000),
  ('mortgage_adviser', 'professional', 'FinancialService', 'clinical_trust', NULL, NULL, 1, 660, unixepoch() * 1000),
  ('consultant', 'professional', 'ProfessionalService', 'clinical_trust', NULL, NULL, 1, 670, unixepoch() * 1000),
  ('marketing_agency', 'professional', 'ProfessionalService', 'clinical_trust', NULL, NULL, 1, 680, unixepoch() * 1000),
  ('it_services', 'professional', 'ProfessionalService', 'midnight_neon', NULL, NULL, 1, 690, unixepoch() * 1000),
  ('recruitment_agency', 'professional', 'EmploymentAgency', 'clinical_trust', NULL, NULL, 1, 700, unixepoch() * 1000),
  ('architect', 'professional', 'ProfessionalService', 'clinical_trust', NULL, NULL, 1, 710, unixepoch() * 1000),
  ('dj', 'events', 'ProfessionalService', 'midnight_neon', 'https://www.wikidata.org/wiki/Q130857', NULL, 1, 720, unixepoch() * 1000),
  ('live_band', 'events', 'ProfessionalService', 'midnight_neon', 'https://schema.org/MusicGroup', NULL, 1, 730, unixepoch() * 1000),
  ('wedding_planner', 'events', 'ProfessionalService', 'warm_trattoria', NULL, NULL, 1, 740, unixepoch() * 1000),
  ('photographer', 'events', 'ProfessionalService', 'clinical_trust', 'https://www.wikidata.org/wiki/Q33231', NULL, 1, 750, unixepoch() * 1000),
  ('videographer', 'events', 'ProfessionalService', 'midnight_neon', 'https://www.wikidata.org/wiki/Q1027872', NULL, 1, 760, unixepoch() * 1000),
  ('nightclub', 'events', 'NightClub', 'midnight_neon', NULL, NULL, 1, 770, unixepoch() * 1000),
  ('party_rental', 'events', 'LocalBusiness', 'warm_trattoria', 'https://www.wikidata.org/wiki/Q1092268', NULL, 1, 780, unixepoch() * 1000),
  ('art_gallery', 'events', 'ArtGallery', 'warm_trattoria', NULL, NULL, 1, 790, unixepoch() * 1000),
  ('language_school', 'education', 'ProfessionalService', 'warm_trattoria', 'https://schema.org/School', NULL, 1, 800, unixepoch() * 1000),
  ('music_school', 'education', 'ProfessionalService', 'warm_trattoria', 'https://schema.org/School', NULL, 1, 810, unixepoch() * 1000),
  ('tutoring', 'education', 'ProfessionalService', 'clinical_trust', 'https://schema.org/EducationalOrganization', NULL, 1, 820, unixepoch() * 1000),
  ('business_coach', 'education', 'ProfessionalService', 'clinical_trust', NULL, NULL, 1, 830, unixepoch() * 1000),
  ('childcare', 'education', 'ChildCare', 'warm_trattoria', NULL, NULL, 1, 840, unixepoch() * 1000),
  ('estate_agent', 'real_estate', 'RealEstateAgent', 'clinical_trust', NULL, NULL, 1, 850, unixepoch() * 1000),
  ('property_manager', 'real_estate', 'RealEstateAgent', 'clinical_trust', NULL, NULL, 1, 860, unixepoch() * 1000),
  ('self_storage', 'real_estate', 'SelfStorage', 'midnight_neon', NULL, NULL, 1, 870, unixepoch() * 1000),
  ('surveyor', 'real_estate', 'ProfessionalService', 'clinical_trust', NULL, NULL, 1, 880, unixepoch() * 1000),
  ('hotel', 'travel', 'Hotel', 'warm_trattoria', NULL, NULL, 1, 890, unixepoch() * 1000),
  ('bed_breakfast', 'travel', 'BedAndBreakfast', 'clinical_trust', NULL, NULL, 1, 900, unixepoch() * 1000),
  ('campsite', 'travel', 'Campground', 'warm_trattoria', NULL, NULL, 1, 910, unixepoch() * 1000),
  ('travel_agency', 'travel', 'TravelAgency', 'warm_trattoria', NULL, NULL, 1, 920, unixepoch() * 1000),
  ('tour_operator', 'travel', 'TravelAgency', 'warm_trattoria', NULL, NULL, 1, 930, unixepoch() * 1000),
  ('veterinarian', 'pets', 'VeterinaryCare', 'clinical_trust', NULL, NULL, 1, 940, unixepoch() * 1000),
  ('pet_grooming', 'pets', 'LocalBusiness', 'clinical_trust', 'https://www.wikidata.org/wiki/Q3355098', NULL, 1, 950, unixepoch() * 1000),
  ('dog_training', 'pets', 'LocalBusiness', 'clinical_trust', 'https://www.wikidata.org/wiki/Q1194479', NULL, 1, 960, unixepoch() * 1000),
  ('equestrian_centre', 'pets', 'SportsActivityLocation', 'warm_trattoria', NULL, NULL, 1, 970, unixepoch() * 1000),
  ('artisan_maker', 'crafts', 'LocalBusiness', 'warm_trattoria', 'https://www.wikidata.org/wiki/Q1294787', NULL, 1, 980, unixepoch() * 1000),
  ('tailor', 'crafts', 'ClothingStore', 'warm_trattoria', 'https://www.wikidata.org/wiki/Q874405', NULL, 1, 990, unixepoch() * 1000),
  ('dry_cleaner', 'crafts', 'DryCleaningOrLaundry', 'clinical_trust', NULL, NULL, 1, 1000, unixepoch() * 1000),
  ('cleaning_company', 'crafts', 'ProfessionalService', 'clinical_trust', NULL, NULL, 1, 1010, unixepoch() * 1000),
  ('print_shop', 'crafts', 'ProfessionalService', 'clinical_trust', NULL, NULL, 1, 1020, unixepoch() * 1000),
  ('funeral_services', 'crafts', 'LocalBusiness', 'clinical_trust', 'https://www.wikidata.org/wiki/Q1195942', NULL, 1, 1030, unixepoch() * 1000),
  ('other', 'crafts', 'LocalBusiness', 'clinical_trust', NULL, NULL, 1, 1040, unixepoch() * 1000)
ON CONFLICT(key) DO UPDATE SET
  group_key = excluded.group_key, schema_org_type = excluded.schema_org_type,
  dna_id = excluded.dna_id, additional_type = excluded.additional_type,
  sort_order = excluded.sort_order;

INSERT INTO industry_translations (industry_key, locale, label, search_terms) VALUES
  ('restaurant', 'nl', 'Restaurant', 'restaurant,eetcafe,bistro,brasserie,eethuis,dining,eatery'),
  ('restaurant', 'en', 'Restaurant', 'restaurant,eetcafe,bistro,brasserie,eethuis,dining,eatery'),
  ('restaurant', 'de', 'Restaurant', NULL),
  ('restaurant', 'fr', 'Restaurant', NULL),
  ('restaurant', 'es', 'Restaurante', NULL),
  ('restaurant', 'pt', 'Restaurante', NULL),
  ('cafe', 'nl', 'Café & lunchroom', 'cafe,koffie,lunchroom,koffiebar,espressobar,coffee,brunch'),
  ('cafe', 'en', 'Café & lunchroom', 'cafe,koffie,lunchroom,koffiebar,espressobar,coffee,brunch'),
  ('cafe', 'de', 'Café & Bistro', NULL),
  ('cafe', 'fr', 'Café & salon de thé', NULL),
  ('cafe', 'es', 'Cafetería', NULL),
  ('cafe', 'pt', 'Café & casa de chá', NULL),
  ('bakery', 'nl', 'Bakkerij & patisserie', 'bakker,bakkerij,brood,banketbakker,taart,bakery,pastry'),
  ('bakery', 'en', 'Bakery & patisserie', 'bakker,bakkerij,brood,banketbakker,taart,bakery,pastry'),
  ('bakery', 'de', 'Bäckerei & Konditorei', NULL),
  ('bakery', 'fr', 'Boulangerie & pâtisserie', NULL),
  ('bakery', 'es', 'Panadería y pastelería', NULL),
  ('bakery', 'pt', 'Padaria e pastelaria', NULL),
  ('bar_pub', 'nl', 'Bar & café', 'bar,kroeg,cafe,pub,bruin cafe,borrel,cocktailbar'),
  ('bar_pub', 'en', 'Bar & pub', 'bar,kroeg,cafe,pub,bruin cafe,borrel,cocktailbar'),
  ('bar_pub', 'de', 'Bar & Kneipe', NULL),
  ('bar_pub', 'fr', 'Bar & pub', NULL),
  ('bar_pub', 'es', 'Bar y pub', NULL),
  ('bar_pub', 'pt', 'Bar e pub', NULL),
  ('takeaway', 'nl', 'Afhaal & fastfood', 'afhaal,snackbar,cafetaria,pizzeria,shoarma,takeaway,friture'),
  ('takeaway', 'en', 'Takeaway & fast food', 'afhaal,snackbar,cafetaria,pizzeria,shoarma,takeaway,friture'),
  ('takeaway', 'de', 'Imbiss & Lieferdienst', NULL),
  ('takeaway', 'fr', 'Vente à emporter & fast-food', NULL),
  ('takeaway', 'es', 'Comida para llevar', NULL),
  ('takeaway', 'pt', 'Comida para levar', NULL),
  ('food_truck', 'nl', 'Foodtruck', 'foodtruck,street food,marktkraam,mobiele keuken,food truck'),
  ('food_truck', 'en', 'Food truck', 'foodtruck,street food,marktkraam,mobiele keuken,food truck'),
  ('food_truck', 'de', 'Foodtruck', NULL),
  ('food_truck', 'fr', 'Food truck', NULL),
  ('food_truck', 'es', 'Food truck', NULL),
  ('food_truck', 'pt', 'Food truck', NULL),
  ('ice_cream', 'nl', 'IJssalon', 'ijssalon,ijs,gelato,ijsboerderij,ice cream,sorbet'),
  ('ice_cream', 'en', 'Ice cream parlour', 'ijssalon,ijs,gelato,ijsboerderij,ice cream,sorbet'),
  ('ice_cream', 'de', 'Eisdiele', NULL),
  ('ice_cream', 'fr', 'Glacier', NULL),
  ('ice_cream', 'es', 'Heladería', NULL),
  ('ice_cream', 'pt', 'Gelataria', NULL),
  ('catering', 'nl', 'Catering', 'catering,partyservice,traiteur,bedrijfscatering,buffet'),
  ('catering', 'en', 'Catering', 'catering,partyservice,traiteur,bedrijfscatering,buffet'),
  ('catering', 'de', 'Catering', NULL),
  ('catering', 'fr', 'Traiteur', NULL),
  ('catering', 'es', 'Catering', NULL),
  ('catering', 'pt', 'Catering', NULL),
  ('brewery', 'nl', 'Brouwerij & distilleerderij', 'brouwerij,bier,distilleerderij,stokerij,brewery,craft beer'),
  ('brewery', 'en', 'Brewery & distillery', 'brouwerij,bier,distilleerderij,stokerij,brewery,craft beer'),
  ('brewery', 'de', 'Brauerei & Destillerie', NULL),
  ('brewery', 'fr', 'Brasserie & distillerie', NULL),
  ('brewery', 'es', 'Cervecería artesanal y destilería', NULL),
  ('brewery', 'pt', 'Cervejaria e destilaria', NULL),
  ('hairdresser', 'nl', 'Kapsalon', 'kapper,kapsalon,haarstylist,coiffure,hairdresser,hair salon'),
  ('hairdresser', 'en', 'Hair salon', 'kapper,kapsalon,haarstylist,coiffure,hairdresser,hair salon'),
  ('hairdresser', 'de', 'Friseursalon', NULL),
  ('hairdresser', 'fr', 'Salon de coiffure', NULL),
  ('hairdresser', 'es', 'Peluquería', NULL),
  ('hairdresser', 'pt', 'Cabeleireiro', NULL),
  ('barbershop', 'nl', 'Barbershop', 'barbier,barbershop,herenkapper,baard,scheren,barber'),
  ('barbershop', 'en', 'Barbershop', 'barbier,barbershop,herenkapper,baard,scheren,barber'),
  ('barbershop', 'de', 'Barbershop', NULL),
  ('barbershop', 'fr', 'Barbier', NULL),
  ('barbershop', 'es', 'Barbería', NULL),
  ('barbershop', 'pt', 'Barbearia', NULL),
  ('beauty_salon', 'nl', 'Schoonheidssalon', 'schoonheidsspecialist,beauty,huidverzorging,gezichtsbehandeling'),
  ('beauty_salon', 'en', 'Beauty salon', 'schoonheidsspecialist,beauty,huidverzorging,gezichtsbehandeling'),
  ('beauty_salon', 'de', 'Kosmetikstudio', NULL),
  ('beauty_salon', 'fr', 'Institut de beauté', NULL),
  ('beauty_salon', 'es', 'Salón de belleza', NULL),
  ('beauty_salon', 'pt', 'Salão de beleza', NULL),
  ('nail_studio', 'nl', 'Nagelstudio', 'nagelstudio,nagels,manicure,pedicure,gellak,nail studio'),
  ('nail_studio', 'en', 'Nail studio', 'nagelstudio,nagels,manicure,pedicure,gellak,nail studio'),
  ('nail_studio', 'de', 'Nagelstudio', NULL),
  ('nail_studio', 'fr', 'Onglerie', NULL),
  ('nail_studio', 'es', 'Salón de uñas', NULL),
  ('nail_studio', 'pt', 'Estúdio de unhas', NULL),
  ('day_spa', 'nl', 'Wellness & sauna', 'wellness,spa,sauna,beautyfarm,hammam,day spa'),
  ('day_spa', 'en', 'Spa & sauna', 'wellness,spa,sauna,beautyfarm,hammam,day spa'),
  ('day_spa', 'de', 'Wellness & Sauna', NULL),
  ('day_spa', 'fr', 'Spa & sauna', NULL),
  ('day_spa', 'es', 'Spa y sauna', NULL),
  ('day_spa', 'pt', 'Spa e sauna', NULL),
  ('massage', 'nl', 'Massagepraktijk', 'massage,masseur,sportmassage,ontspanningsmassage,shiatsu'),
  ('massage', 'en', 'Massage therapy', 'massage,masseur,sportmassage,ontspanningsmassage,shiatsu'),
  ('massage', 'de', 'Massagepraxis', NULL),
  ('massage', 'fr', 'Cabinet de massage', NULL),
  ('massage', 'es', 'Centro de masajes', NULL),
  ('massage', 'pt', 'Massagem terapêutica', NULL),
  ('tattoo_studio', 'nl', 'Tattoo & piercing', 'tattoo,tatoeage,piercing,tattooshop,inkt,tattoo studio'),
  ('tattoo_studio', 'en', 'Tattoo & piercing', 'tattoo,tatoeage,piercing,tattooshop,inkt,tattoo studio'),
  ('tattoo_studio', 'de', 'Tattoo & Piercing', NULL),
  ('tattoo_studio', 'fr', 'Tatouage & piercing', NULL),
  ('tattoo_studio', 'es', 'Tatuajes y piercings', NULL),
  ('tattoo_studio', 'pt', 'Tatuagens e piercings', NULL),
  ('gp_practice', 'nl', 'Huisartsenpraktijk', 'huisarts,dokter,huisartsenpraktijk,medisch centrum,gp,doctor'),
  ('gp_practice', 'en', 'GP practice', 'huisarts,dokter,huisartsenpraktijk,medisch centrum,gp,doctor'),
  ('gp_practice', 'de', 'Hausarztpraxis', NULL),
  ('gp_practice', 'fr', 'Cabinet de médecine générale', NULL),
  ('gp_practice', 'es', 'Consulta de medicina general', NULL),
  ('gp_practice', 'pt', 'Clínica de medicina geral', NULL),
  ('dentist', 'nl', 'Tandartspraktijk', 'tandarts,mondhygienist,orthodontist,gebit,dentist,dental'),
  ('dentist', 'en', 'Dental practice', 'tandarts,mondhygienist,orthodontist,gebit,dentist,dental'),
  ('dentist', 'de', 'Zahnarztpraxis', NULL),
  ('dentist', 'fr', 'Cabinet dentaire', NULL),
  ('dentist', 'es', 'Clínica dental', NULL),
  ('dentist', 'pt', 'Clínica dentária', NULL),
  ('physiotherapist', 'nl', 'Fysiotherapie', 'fysio,fysiotherapie,manueel therapeut,revalidatie,physio'),
  ('physiotherapist', 'en', 'Physiotherapy', 'fysio,fysiotherapie,manueel therapeut,revalidatie,physio'),
  ('physiotherapist', 'de', 'Physiotherapie', NULL),
  ('physiotherapist', 'fr', 'Kinésithérapie', NULL),
  ('physiotherapist', 'es', 'Fisioterapia', NULL),
  ('physiotherapist', 'pt', 'Fisioterapia', NULL),
  ('chiropractor', 'nl', 'Chiropractor & osteopaat', 'chiropractor,osteopaat,rug,nek,chiropractic,osteopath'),
  ('chiropractor', 'en', 'Chiropractor & osteopath', 'chiropractor,osteopaat,rug,nek,chiropractic,osteopath'),
  ('chiropractor', 'de', 'Chiropraktik & Osteopathie', NULL),
  ('chiropractor', 'fr', 'Chiropracteur & ostéopathe', NULL),
  ('chiropractor', 'es', 'Quiropráctico y osteópata', NULL),
  ('chiropractor', 'pt', 'Quiroprático e osteopata', NULL),
  ('psychologist', 'nl', 'Psycholoog & therapie', 'psycholoog,therapeut,ggz,coaching,psychologist,therapy'),
  ('psychologist', 'en', 'Psychologist & therapy', 'psycholoog,therapeut,ggz,coaching,psychologist,therapy'),
  ('psychologist', 'de', 'Psychologe & Therapie', NULL),
  ('psychologist', 'fr', 'Psychologue & thérapie', NULL),
  ('psychologist', 'es', 'Psicólogo y terapia', NULL),
  ('psychologist', 'pt', 'Psicólogo e terapia', NULL),
  ('optician', 'nl', 'Opticien', 'opticien,brillen,oogmeting,contactlenzen,optician,glasses'),
  ('optician', 'en', 'Optician', 'opticien,brillen,oogmeting,contactlenzen,optician,glasses'),
  ('optician', 'de', 'Optiker', NULL),
  ('optician', 'fr', 'Opticien', NULL),
  ('optician', 'es', 'Óptica', NULL),
  ('optician', 'pt', 'Ótica', NULL),
  ('pharmacy', 'nl', 'Apotheek', 'apotheek,drogist,medicijnen,recept,pharmacy,chemist'),
  ('pharmacy', 'en', 'Pharmacy', 'apotheek,drogist,medicijnen,recept,pharmacy,chemist'),
  ('pharmacy', 'de', 'Apotheke', NULL),
  ('pharmacy', 'fr', 'Pharmacie', NULL),
  ('pharmacy', 'es', 'Farmacia', NULL),
  ('pharmacy', 'pt', 'Farmácia', NULL),
  ('home_care', 'nl', 'Thuiszorg', 'thuiszorg,verpleging,mantelzorg,wijkverpleging,home care'),
  ('home_care', 'en', 'Home care', 'thuiszorg,verpleging,mantelzorg,wijkverpleging,home care'),
  ('home_care', 'de', 'Häusliche Pflege', NULL),
  ('home_care', 'fr', 'Aide à domicile', NULL),
  ('home_care', 'es', 'Ayuda a domicilio', NULL),
  ('home_care', 'pt', 'Apoio domiciliário', NULL),
  ('gym', 'nl', 'Sportschool', 'sportschool,fitness,gym,krachttraining,health club'),
  ('gym', 'en', 'Gym & fitness', 'sportschool,fitness,gym,krachttraining,health club'),
  ('gym', 'de', 'Fitnessstudio', NULL),
  ('gym', 'fr', 'Salle de sport', NULL),
  ('gym', 'es', 'Gimnasio', NULL),
  ('gym', 'pt', 'Ginásio', NULL),
  ('crossfit_box', 'nl', 'CrossFit & functional', 'crossfit,box,bootcamp,functional training,hyrox'),
  ('crossfit_box', 'en', 'CrossFit & functional', 'crossfit,box,bootcamp,functional training,hyrox'),
  ('crossfit_box', 'de', 'CrossFit & Functional', NULL),
  ('crossfit_box', 'fr', 'CrossFit & training fonctionnel', NULL),
  ('crossfit_box', 'es', 'CrossFit y entrenamiento funcional', NULL),
  ('crossfit_box', 'pt', 'CrossFit e treino funcional', NULL),
  ('yoga_studio', 'nl', 'Yoga & pilates', 'yoga,pilates,yogastudio,meditatie,ashtanga,vinyasa'),
  ('yoga_studio', 'en', 'Yoga & pilates', 'yoga,pilates,yogastudio,meditatie,ashtanga,vinyasa'),
  ('yoga_studio', 'de', 'Yoga & Pilates', NULL),
  ('yoga_studio', 'fr', 'Yoga & pilates', NULL),
  ('yoga_studio', 'es', 'Yoga y pilates', NULL),
  ('yoga_studio', 'pt', 'Ioga e pilates', NULL),
  ('personal_trainer', 'nl', 'Personal trainer', 'personal trainer,pt,leefstijlcoach,voedingsadvies,coach'),
  ('personal_trainer', 'en', 'Personal trainer', 'personal trainer,pt,leefstijlcoach,voedingsadvies,coach'),
  ('personal_trainer', 'de', 'Personal Trainer', NULL),
  ('personal_trainer', 'fr', 'Coach sportif', NULL),
  ('personal_trainer', 'es', 'Entrenador personal', NULL),
  ('personal_trainer', 'pt', 'Personal trainer', NULL),
  ('martial_arts', 'nl', 'Vechtsport & boksen', 'vechtsport,boksen,kickboksen,judo,karate,bjj,mma'),
  ('martial_arts', 'en', 'Martial arts & boxing', 'vechtsport,boksen,kickboksen,judo,karate,bjj,mma'),
  ('martial_arts', 'de', 'Kampfsport & Boxen', NULL),
  ('martial_arts', 'fr', 'Arts martiaux & boxe', NULL),
  ('martial_arts', 'es', 'Artes marciales y boxeo', NULL),
  ('martial_arts', 'pt', 'Artes marciais e boxe', NULL),
  ('dance_school', 'nl', 'Dansschool', 'dansschool,dansen,ballet,salsa,streetdance,dance'),
  ('dance_school', 'en', 'Dance school', 'dansschool,dansen,ballet,salsa,streetdance,dance'),
  ('dance_school', 'de', 'Tanzschule', NULL),
  ('dance_school', 'fr', 'École de danse', NULL),
  ('dance_school', 'es', 'Escuela de baile', NULL),
  ('dance_school', 'pt', 'Escola de dança', NULL),
  ('racket_club', 'nl', 'Tennis, padel & golf', 'tennis,padel,golf,squash,racketclub,tennisbaan'),
  ('racket_club', 'en', 'Tennis, padel & golf', 'tennis,padel,golf,squash,racketclub,tennisbaan'),
  ('racket_club', 'de', 'Tennis, Padel & Golf', NULL),
  ('racket_club', 'fr', 'Tennis, padel & golf', NULL),
  ('racket_club', 'es', 'Tenis, pádel y golf', NULL),
  ('racket_club', 'pt', 'Ténis, padel e golfe', NULL),
  ('plumber', 'nl', 'Loodgieter', 'loodgieter,sanitair,lekkage,riool,plumber,badkamer'),
  ('plumber', 'en', 'Plumber', 'loodgieter,sanitair,lekkage,riool,plumber,badkamer'),
  ('plumber', 'de', 'Klempner', NULL),
  ('plumber', 'fr', 'Plombier', NULL),
  ('plumber', 'es', 'Fontanería', NULL),
  ('plumber', 'pt', 'Canalizador', NULL),
  ('electrician', 'nl', 'Elektricien', 'elektricien,installateur,groepenkast,laadpaal,electrician'),
  ('electrician', 'en', 'Electrician', 'elektricien,installateur,groepenkast,laadpaal,electrician'),
  ('electrician', 'de', 'Elektriker', NULL),
  ('electrician', 'fr', 'Électricien', NULL),
  ('electrician', 'es', 'Electricista', NULL),
  ('electrician', 'pt', 'Eletricista', NULL),
  ('hvac_heatpump', 'nl', 'Cv, koeling & warmtepompen', 'cv ketel,warmtepomp,airco,verwarming,koeling,hvac'),
  ('hvac_heatpump', 'en', 'Heating, cooling & heat pumps', 'cv ketel,warmtepomp,airco,verwarming,koeling,hvac'),
  ('hvac_heatpump', 'de', 'Heizung, Kühlung & Wärmepumpen', NULL),
  ('hvac_heatpump', 'fr', 'Chauffage, climatisation & pompes à chaleur', NULL),
  ('hvac_heatpump', 'es', 'Calefacción, climatización y bombas de calor', NULL),
  ('hvac_heatpump', 'pt', 'Aquecimento, climatização e bombas de calor', NULL),
  ('general_contractor', 'nl', 'Aannemer', 'aannemer,bouwbedrijf,verbouwing,metselaar,contractor,builder'),
  ('general_contractor', 'en', 'Builder & contractor', 'aannemer,bouwbedrijf,verbouwing,metselaar,contractor,builder'),
  ('general_contractor', 'de', 'Bauunternehmen', NULL),
  ('general_contractor', 'fr', 'Entreprise de construction', NULL),
  ('general_contractor', 'es', 'Empresa constructora', NULL),
  ('general_contractor', 'pt', 'Empresa de construção', NULL),
  ('painter_decorator', 'nl', 'Schilder & stukadoor', 'schilder,schilderwerk,stukadoor,behanger,painter,decorator'),
  ('painter_decorator', 'en', 'Painter & decorator', 'schilder,schilderwerk,stukadoor,behanger,painter,decorator'),
  ('painter_decorator', 'de', 'Maler & Stuckateur', NULL),
  ('painter_decorator', 'fr', 'Peintre & plâtrier', NULL),
  ('painter_decorator', 'es', 'Pintor y yesero', NULL),
  ('painter_decorator', 'pt', 'Pintor e estucador', NULL),
  ('roofer', 'nl', 'Dakdekker', 'dakdekker,dak,dakbedekking,dakgoot,roofer,lekkend dak'),
  ('roofer', 'en', 'Roofer', 'dakdekker,dak,dakbedekking,dakgoot,roofer,lekkend dak'),
  ('roofer', 'de', 'Dachdecker', NULL),
  ('roofer', 'fr', 'Couvreur', NULL),
  ('roofer', 'es', 'Tejados y cubiertas', NULL),
  ('roofer', 'pt', 'Coberturas e telhados', NULL),
  ('carpenter', 'nl', 'Timmerman & meubelmaker', 'timmerman,meubelmaker,kozijnen,interieurbouw,carpenter'),
  ('carpenter', 'en', 'Carpenter & joinery', 'timmerman,meubelmaker,kozijnen,interieurbouw,carpenter'),
  ('carpenter', 'de', 'Tischlerei & Schreinerei', NULL),
  ('carpenter', 'fr', 'Menuiserie & ébénisterie', NULL),
  ('carpenter', 'es', 'Carpintería y ebanistería', NULL),
  ('carpenter', 'pt', 'Carpintaria e marcenaria', NULL),
  ('locksmith', 'nl', 'Slotenmaker', 'slotenmaker,sloten,buitengesloten,inbraakbeveiliging,locksmith'),
  ('locksmith', 'en', 'Locksmith', 'slotenmaker,sloten,buitengesloten,inbraakbeveiliging,locksmith'),
  ('locksmith', 'de', 'Schlüsseldienst', NULL),
  ('locksmith', 'fr', 'Serrurier', NULL),
  ('locksmith', 'es', 'Cerrajería', NULL),
  ('locksmith', 'pt', 'Serralharia', NULL),
  ('landscaper', 'nl', 'Hovenier & tuinaanleg', 'hovenier,tuinman,tuinaanleg,bestrating,gardener,landscaping'),
  ('landscaper', 'en', 'Gardener & landscaping', 'hovenier,tuinman,tuinaanleg,bestrating,gardener,landscaping'),
  ('landscaper', 'de', 'Garten- & Landschaftsbau', NULL),
  ('landscaper', 'fr', 'Paysagiste & jardinier', NULL),
  ('landscaper', 'es', 'Jardinería y paisajismo', NULL),
  ('landscaper', 'pt', 'Jardinagem e paisagismo', NULL),
  ('solar_installer', 'nl', 'Zonnepanelen & energie', 'zonnepanelen,solar,thuisbatterij,isolatie,energieadvies'),
  ('solar_installer', 'en', 'Solar & energy', 'zonnepanelen,solar,thuisbatterij,isolatie,energieadvies'),
  ('solar_installer', 'de', 'Solaranlagen & Energie', NULL),
  ('solar_installer', 'fr', 'Panneaux solaires & énergie', NULL),
  ('solar_installer', 'es', 'Placas solares y energía', NULL),
  ('solar_installer', 'pt', 'Painéis solares e energia', NULL),
  ('car_repair', 'nl', 'Autogarage', 'garage,automonteur,apk,onderhoud,car repair,werkplaats'),
  ('car_repair', 'en', 'Garage & repair', 'garage,automonteur,apk,onderhoud,car repair,werkplaats'),
  ('car_repair', 'de', 'Autowerkstatt', NULL),
  ('car_repair', 'fr', 'Garage automobile', NULL),
  ('car_repair', 'es', 'Taller mecánico', NULL),
  ('car_repair', 'pt', 'Oficina automóvel', NULL),
  ('car_dealer', 'nl', 'Autodealer', 'autodealer,occasions,autobedrijf,showroom,car dealer'),
  ('car_dealer', 'en', 'Car dealer', 'autodealer,occasions,autobedrijf,showroom,car dealer'),
  ('car_dealer', 'de', 'Autohaus', NULL),
  ('car_dealer', 'fr', 'Concessionnaire automobile', NULL),
  ('car_dealer', 'es', 'Concesionario', NULL),
  ('car_dealer', 'pt', 'Stand automóvel', NULL),
  ('car_bodywork', 'nl', 'Autoschadeherstel', 'autoschade,plaatwerk,spuiterij,deuk,bodyshop,ruitschade'),
  ('car_bodywork', 'en', 'Bodywork & paint', 'autoschade,plaatwerk,spuiterij,deuk,bodyshop,ruitschade'),
  ('car_bodywork', 'de', 'Karosserie & Lack', NULL),
  ('car_bodywork', 'fr', 'Carrosserie & peinture', NULL),
  ('car_bodywork', 'es', 'Chapa y pintura', NULL),
  ('car_bodywork', 'pt', 'Chapa e pintura', NULL),
  ('tyre_service', 'nl', 'Bandenservice', 'banden,bandenservice,velgen,winterbanden,tyres,uitlijnen'),
  ('tyre_service', 'en', 'Tyres & wheels', 'banden,bandenservice,velgen,winterbanden,tyres,uitlijnen'),
  ('tyre_service', 'de', 'Reifenservice', NULL),
  ('tyre_service', 'fr', 'Pneus & jantes', NULL),
  ('tyre_service', 'es', 'Neumáticos y llantas', NULL),
  ('tyre_service', 'pt', 'Pneus e jantes', NULL),
  ('car_wash', 'nl', 'Carwash & detailing', 'carwash,autowasserette,poetsen,detailing,coating,car wash'),
  ('car_wash', 'en', 'Car wash & detailing', 'carwash,autowasserette,poetsen,detailing,coating,car wash'),
  ('car_wash', 'de', 'Autowäsche & Aufbereitung', NULL),
  ('car_wash', 'fr', 'Lavage auto & detailing', NULL),
  ('car_wash', 'es', 'Lavado de coches y detailing', NULL),
  ('car_wash', 'pt', 'Lavagem auto e detailing', NULL),
  ('bike_shop', 'nl', 'Fietsenwinkel & reparatie', 'fietsenmaker,fietsenwinkel,ebike,fietsreparatie,bike shop'),
  ('bike_shop', 'en', 'Bicycle shop & repair', 'fietsenmaker,fietsenwinkel,ebike,fietsreparatie,bike shop'),
  ('bike_shop', 'de', 'Fahrradladen & Werkstatt', NULL),
  ('bike_shop', 'fr', 'Magasin & réparation de vélos', NULL),
  ('bike_shop', 'es', 'Tienda y taller de bicicletas', NULL),
  ('bike_shop', 'pt', 'Loja e oficina de bicicletas', NULL),
  ('driving_school', 'nl', 'Rijschool', 'rijschool,rijles,rijbewijs,motorrijschool,driving school'),
  ('driving_school', 'en', 'Driving school', 'rijschool,rijles,rijbewijs,motorrijschool,driving school'),
  ('driving_school', 'de', 'Fahrschule', NULL),
  ('driving_school', 'fr', 'Auto-école', NULL),
  ('driving_school', 'es', 'Autoescuela', NULL),
  ('driving_school', 'pt', 'Escola de condução', NULL),
  ('clothing_store', 'nl', 'Kleding & mode', 'kledingwinkel,mode,boetiek,damesmode,herenmode,fashion'),
  ('clothing_store', 'en', 'Clothing & fashion', 'kledingwinkel,mode,boetiek,damesmode,herenmode,fashion'),
  ('clothing_store', 'de', 'Mode & Bekleidung', NULL),
  ('clothing_store', 'fr', 'Vêtements & mode', NULL),
  ('clothing_store', 'es', 'Ropa y moda', NULL),
  ('clothing_store', 'pt', 'Roupa e moda', NULL),
  ('shoe_store', 'nl', 'Schoenen & lederwaren', 'schoenenwinkel,schoenen,tassen,lederwaren,shoes,sneakers'),
  ('shoe_store', 'en', 'Shoes & leather', 'schoenenwinkel,schoenen,tassen,lederwaren,shoes,sneakers'),
  ('shoe_store', 'de', 'Schuhe & Lederwaren', NULL),
  ('shoe_store', 'fr', 'Chaussures & maroquinerie', NULL),
  ('shoe_store', 'es', 'Calzado y marroquinería', NULL),
  ('shoe_store', 'pt', 'Calçado e marroquinaria', NULL),
  ('jeweller', 'nl', 'Juwelier & horloges', 'juwelier,sieraden,horloges,goudsmid,trouwringen,jewellery'),
  ('jeweller', 'en', 'Jewellery & watches', 'juwelier,sieraden,horloges,goudsmid,trouwringen,jewellery'),
  ('jeweller', 'de', 'Juwelier & Uhren', NULL),
  ('jeweller', 'fr', 'Bijouterie & horlogerie', NULL),
  ('jeweller', 'es', 'Joyería y relojería', NULL),
  ('jeweller', 'pt', 'Joalharia e relojoaria', NULL),
  ('florist', 'nl', 'Bloemist', 'bloemist,bloemen,boeket,bloemenwinkel,florist,rouwbloemen'),
  ('florist', 'en', 'Florist', 'bloemist,bloemen,boeket,bloemenwinkel,florist,rouwbloemen'),
  ('florist', 'de', 'Blumenladen', NULL),
  ('florist', 'fr', 'Fleuriste', NULL),
  ('florist', 'es', 'Floristería', NULL),
  ('florist', 'pt', 'Florista', NULL),
  ('bookshop', 'nl', 'Boekhandel & kantoorartikelen', 'boekhandel,boeken,kantoorboekhandel,tijdschriften,bookshop'),
  ('bookshop', 'en', 'Bookshop & stationery', 'boekhandel,boeken,kantoorboekhandel,tijdschriften,bookshop'),
  ('bookshop', 'de', 'Buchhandlung & Schreibwaren', NULL),
  ('bookshop', 'fr', 'Librairie & papeterie', NULL),
  ('bookshop', 'es', 'Librería y papelería', NULL),
  ('bookshop', 'pt', 'Livraria e papelaria', NULL),
  ('toy_store', 'nl', 'Speelgoed & baby', 'speelgoedwinkel,speelgoed,babyspullen,kinderwagen,toys'),
  ('toy_store', 'en', 'Toys & baby', 'speelgoedwinkel,speelgoed,babyspullen,kinderwagen,toys'),
  ('toy_store', 'de', 'Spielwaren & Baby', NULL),
  ('toy_store', 'fr', 'Jouets & puériculture', NULL),
  ('toy_store', 'es', 'Juguetes y bebé', NULL),
  ('toy_store', 'pt', 'Brinquedos e bebé', NULL),
  ('furniture_store', 'nl', 'Meubels & wonen', 'meubelwinkel,meubels,woonwinkel,interieur,furniture,bankstel'),
  ('furniture_store', 'en', 'Furniture & interior', 'meubelwinkel,meubels,woonwinkel,interieur,furniture,bankstel'),
  ('furniture_store', 'de', 'Möbel & Wohnen', NULL),
  ('furniture_store', 'fr', 'Meubles & décoration', NULL),
  ('furniture_store', 'es', 'Muebles y decoración', NULL),
  ('furniture_store', 'pt', 'Móveis e decoração', NULL),
  ('electronics_store', 'nl', 'Elektronica & telefoons', 'elektronica,telefoonwinkel,computerwinkel,reparatie,electronics'),
  ('electronics_store', 'en', 'Electronics & phones', 'elektronica,telefoonwinkel,computerwinkel,reparatie,electronics'),
  ('electronics_store', 'de', 'Elektronik & Handys', NULL),
  ('electronics_store', 'fr', 'Électronique & téléphonie', NULL),
  ('electronics_store', 'es', 'Electrónica y telefonía', NULL),
  ('electronics_store', 'pt', 'Eletrónica e telemóveis', NULL),
  ('sports_store', 'nl', 'Sport & outdoor', 'sportwinkel,sportzaak,outdoor,hardloopwinkel,sports store'),
  ('sports_store', 'en', 'Sports & outdoor', 'sportwinkel,sportzaak,outdoor,hardloopwinkel,sports store'),
  ('sports_store', 'de', 'Sport & Outdoor', NULL),
  ('sports_store', 'fr', 'Sport & plein air', NULL),
  ('sports_store', 'es', 'Deporte y aire libre', NULL),
  ('sports_store', 'pt', 'Desporto e ar livre', NULL),
  ('pet_store', 'nl', 'Dierenwinkel', 'dierenwinkel,dierenspeciaalzaak,diervoeding,aquarium,pet shop'),
  ('pet_store', 'en', 'Pet shop', 'dierenwinkel,dierenspeciaalzaak,diervoeding,aquarium,pet shop'),
  ('pet_store', 'de', 'Zoofachhandel', NULL),
  ('pet_store', 'fr', 'Animalerie', NULL),
  ('pet_store', 'es', 'Tienda de mascotas', NULL),
  ('pet_store', 'pt', 'Loja de animais', NULL),
  ('butcher', 'nl', 'Slagerij', 'slager,slagerij,vlees,worst,barbecue,butcher,poelier'),
  ('butcher', 'en', 'Butcher', 'slager,slagerij,vlees,worst,barbecue,butcher,poelier'),
  ('butcher', 'de', 'Metzgerei', NULL),
  ('butcher', 'fr', 'Boucherie', NULL),
  ('butcher', 'es', 'Carnicería', NULL),
  ('butcher', 'pt', 'Talho', NULL),
  ('farm_shop', 'nl', 'Groentewinkel & boerderijwinkel', 'groenteboer,boerderijwinkel,streekproducten,markt,farm shop'),
  ('farm_shop', 'en', 'Greengrocer & farm shop', 'groenteboer,boerderijwinkel,streekproducten,markt,farm shop'),
  ('farm_shop', 'de', 'Gemüseladen & Hofladen', NULL),
  ('farm_shop', 'fr', 'Primeur & magasin de ferme', NULL),
  ('farm_shop', 'es', 'Frutería y tienda de granja', NULL),
  ('farm_shop', 'pt', 'Frutaria e loja da quinta', NULL),
  ('accountant', 'nl', 'Accountant & boekhouder', 'accountant,boekhouder,administratiekantoor,jaarrekening,btw'),
  ('accountant', 'en', 'Accountant & bookkeeper', 'accountant,boekhouder,administratiekantoor,jaarrekening,btw'),
  ('accountant', 'de', 'Buchhaltung & Rechnungswesen', NULL),
  ('accountant', 'fr', 'Expert-comptable', NULL),
  ('accountant', 'es', 'Asesoría contable', NULL),
  ('accountant', 'pt', 'Contabilidade', NULL),
  ('lawyer', 'nl', 'Advocaat', 'advocaat,advocatenkantoor,juridisch advies,lawyer,mediation'),
  ('lawyer', 'en', 'Lawyer', 'advocaat,advocatenkantoor,juridisch advies,lawyer,mediation'),
  ('lawyer', 'de', 'Rechtsanwalt', NULL),
  ('lawyer', 'fr', 'Avocat', NULL),
  ('lawyer', 'es', 'Abogado', NULL),
  ('lawyer', 'pt', 'Advogado', NULL),
  ('notary', 'nl', 'Notaris', 'notaris,notariskantoor,testament,akte,notary,hypotheekakte'),
  ('notary', 'en', 'Notary', 'notaris,notariskantoor,testament,akte,notary,hypotheekakte'),
  ('notary', 'de', 'Notar', NULL),
  ('notary', 'fr', 'Notaire', NULL),
  ('notary', 'es', 'Notaría', NULL),
  ('notary', 'pt', 'Notário', NULL),
  ('tax_adviser', 'nl', 'Belastingadviseur', 'belastingadviseur,belastingaangifte,fiscalist,tax adviser'),
  ('tax_adviser', 'en', 'Tax adviser', 'belastingadviseur,belastingaangifte,fiscalist,tax adviser'),
  ('tax_adviser', 'de', 'Steuerberater', NULL),
  ('tax_adviser', 'fr', 'Conseiller fiscal', NULL),
  ('tax_adviser', 'es', 'Asesor fiscal', NULL),
  ('tax_adviser', 'pt', 'Consultor fiscal', NULL),
  ('insurance_broker', 'nl', 'Verzekeringsadviseur', 'verzekeringen,assurantiekantoor,tussenpersoon,insurance broker'),
  ('insurance_broker', 'en', 'Insurance broker', 'verzekeringen,assurantiekantoor,tussenpersoon,insurance broker'),
  ('insurance_broker', 'de', 'Versicherungsmakler', NULL),
  ('insurance_broker', 'fr', 'Courtier en assurances', NULL),
  ('insurance_broker', 'es', 'Corredor de seguros', NULL),
  ('insurance_broker', 'pt', 'Corretor de seguros', NULL),
  ('mortgage_adviser', 'nl', 'Hypotheek- & financieel advies', 'hypotheekadviseur,hypotheek,financieel advies,mortgage adviser'),
  ('mortgage_adviser', 'en', 'Mortgage & financial advice', 'hypotheekadviseur,hypotheek,financieel advies,mortgage adviser'),
  ('mortgage_adviser', 'de', 'Baufinanzierung & Finanzberatung', NULL),
  ('mortgage_adviser', 'fr', 'Courtier en crédit & conseil financier', NULL),
  ('mortgage_adviser', 'es', 'Asesoría hipotecaria y financiera', NULL),
  ('mortgage_adviser', 'pt', 'Crédito habitação e consultoria financeira', NULL),
  ('consultant', 'nl', 'Adviesbureau', 'adviesbureau,consultant,interim,bedrijfsadvies,consultancy'),
  ('consultant', 'en', 'Consultant', 'adviesbureau,consultant,interim,bedrijfsadvies,consultancy'),
  ('consultant', 'de', 'Unternehmensberatung', NULL),
  ('consultant', 'fr', 'Cabinet de conseil', NULL),
  ('consultant', 'es', 'Consultoría', NULL),
  ('consultant', 'pt', 'Consultoria', NULL),
  ('marketing_agency', 'nl', 'Marketing- & reclamebureau', 'marketingbureau,reclamebureau,seo,social media,marketing'),
  ('marketing_agency', 'en', 'Marketing & advertising', 'marketingbureau,reclamebureau,seo,social media,marketing'),
  ('marketing_agency', 'de', 'Marketing- & Werbeagentur', NULL),
  ('marketing_agency', 'fr', 'Agence de marketing & publicité', NULL),
  ('marketing_agency', 'es', 'Agencia de marketing y publicidad', NULL),
  ('marketing_agency', 'pt', 'Agência de marketing e publicidade', NULL),
  ('it_services', 'nl', 'IT-diensten & webdesign', 'ict,it beheer,webdesign,softwarebedrijf,systeembeheer,it'),
  ('it_services', 'en', 'IT services & web', 'ict,it beheer,webdesign,softwarebedrijf,systeembeheer,it'),
  ('it_services', 'de', 'IT-Dienstleistungen & Web', NULL),
  ('it_services', 'fr', 'Services informatiques & web', NULL),
  ('it_services', 'es', 'Servicios informáticos y web', NULL),
  ('it_services', 'pt', 'Serviços de TI e web', NULL),
  ('recruitment_agency', 'nl', 'Werving & uitzendbureau', 'uitzendbureau,recruitment,werving en selectie,detachering'),
  ('recruitment_agency', 'en', 'Recruitment & staffing', 'uitzendbureau,recruitment,werving en selectie,detachering'),
  ('recruitment_agency', 'de', 'Personalvermittlung & Zeitarbeit', NULL),
  ('recruitment_agency', 'fr', 'Recrutement & intérim', NULL),
  ('recruitment_agency', 'es', 'Selección y trabajo temporal', NULL),
  ('recruitment_agency', 'pt', 'Recrutamento e trabalho temporário', NULL),
  ('architect', 'nl', 'Architect & ingenieursbureau', 'architect,architectenbureau,bouwkundig,ingenieursbureau'),
  ('architect', 'en', 'Architect & engineering', 'architect,architectenbureau,bouwkundig,ingenieursbureau'),
  ('architect', 'de', 'Architektur- & Ingenieurbüro', NULL),
  ('architect', 'fr', 'Architecte & bureau d''études', NULL),
  ('architect', 'es', 'Arquitectura e ingeniería', NULL),
  ('architect', 'pt', 'Arquitetura e engenharia', NULL),
  ('dj', 'nl', 'DJ', 'dj,discjockey,drive-in show,bruiloft dj,feest dj'),
  ('dj', 'en', 'DJ', 'dj,discjockey,drive-in show,bruiloft dj,feest dj'),
  ('dj', 'de', 'DJ', NULL),
  ('dj', 'fr', 'DJ', NULL),
  ('dj', 'es', 'DJ', NULL),
  ('dj', 'pt', 'DJ', NULL),
  ('live_band', 'nl', 'Band & muzikant', 'band,muzikant,coverband,live muziek,zanger,musician'),
  ('live_band', 'en', 'Band & musician', 'band,muzikant,coverband,live muziek,zanger,musician'),
  ('live_band', 'de', 'Band & Musiker', NULL),
  ('live_band', 'fr', 'Groupe & musicien', NULL),
  ('live_band', 'es', 'Grupo y músico', NULL),
  ('live_band', 'pt', 'Banda e músico', NULL),
  ('wedding_planner', 'nl', 'Bruiloft- & eventplanner', 'weddingplanner,bruiloft,trouwen,eventbureau,ceremoniemeester'),
  ('wedding_planner', 'en', 'Wedding & event planner', 'weddingplanner,bruiloft,trouwen,eventbureau,ceremoniemeester'),
  ('wedding_planner', 'de', 'Hochzeits- & Eventplanung', NULL),
  ('wedding_planner', 'fr', 'Organisation de mariages & d''événements', NULL),
  ('wedding_planner', 'es', 'Organización de bodas y eventos', NULL),
  ('wedding_planner', 'pt', 'Organização de casamentos e eventos', NULL),
  ('photographer', 'nl', 'Fotograaf', 'fotograaf,fotostudio,bruidsfotograaf,portret,photographer'),
  ('photographer', 'en', 'Photographer', 'fotograaf,fotostudio,bruidsfotograaf,portret,photographer'),
  ('photographer', 'de', 'Fotograf', NULL),
  ('photographer', 'fr', 'Photographe', NULL),
  ('photographer', 'es', 'Fotógrafo', NULL),
  ('photographer', 'pt', 'Fotógrafo', NULL),
  ('videographer', 'nl', 'Videograaf', 'videograaf,videoproductie,bedrijfsfilm,drone,videographer'),
  ('videographer', 'en', 'Videographer', 'videograaf,videoproductie,bedrijfsfilm,drone,videographer'),
  ('videographer', 'de', 'Videograf', NULL),
  ('videographer', 'fr', 'Vidéaste', NULL),
  ('videographer', 'es', 'Videógrafo', NULL),
  ('videographer', 'pt', 'Videógrafo', NULL),
  ('nightclub', 'nl', 'Nachtclub', 'nachtclub,discotheek,club,uitgaan,nightclub,dansen'),
  ('nightclub', 'en', 'Nightclub', 'nachtclub,discotheek,club,uitgaan,nightclub,dansen'),
  ('nightclub', 'de', 'Nachtclub', NULL),
  ('nightclub', 'fr', 'Boîte de nuit', NULL),
  ('nightclub', 'es', 'Discoteca', NULL),
  ('nightclub', 'pt', 'Discoteca', NULL),
  ('party_rental', 'nl', 'Feest- & materiaalverhuur', 'partyverhuur,verhuur,springkussen,tentverhuur,party rental'),
  ('party_rental', 'en', 'Party & equipment rental', 'partyverhuur,verhuur,springkussen,tentverhuur,party rental'),
  ('party_rental', 'de', 'Party- & Geräteverleih', NULL),
  ('party_rental', 'fr', 'Location de matériel de fête', NULL),
  ('party_rental', 'es', 'Alquiler para fiestas y eventos', NULL),
  ('party_rental', 'pt', 'Aluguer de material para festas', NULL),
  ('art_gallery', 'nl', 'Kunstgalerie', 'galerie,kunst,expositie,atelier,art gallery,lijstenmaker'),
  ('art_gallery', 'en', 'Art gallery', 'galerie,kunst,expositie,atelier,art gallery,lijstenmaker'),
  ('art_gallery', 'de', 'Kunstgalerie', NULL),
  ('art_gallery', 'fr', 'Galerie d''art', NULL),
  ('art_gallery', 'es', 'Galería de arte', NULL),
  ('art_gallery', 'pt', 'Galeria de arte', NULL),
  ('language_school', 'nl', 'Talenschool', 'taalschool,talenschool,nt2,inburgering,language school'),
  ('language_school', 'en', 'Language school', 'taalschool,talenschool,nt2,inburgering,language school'),
  ('language_school', 'de', 'Sprachschule', NULL),
  ('language_school', 'fr', 'École de langues', NULL),
  ('language_school', 'es', 'Escuela de idiomas', NULL),
  ('language_school', 'pt', 'Escola de línguas', NULL),
  ('music_school', 'nl', 'Muziekschool', 'muziekschool,muziekles,gitaarles,pianoles,zangles'),
  ('music_school', 'en', 'Music school', 'muziekschool,muziekles,gitaarles,pianoles,zangles'),
  ('music_school', 'de', 'Musikschule', NULL),
  ('music_school', 'fr', 'École de musique', NULL),
  ('music_school', 'es', 'Escuela de música', NULL),
  ('music_school', 'pt', 'Escola de música', NULL),
  ('tutoring', 'nl', 'Bijles & examentraining', 'bijles,huiswerkbegeleiding,examentraining,tutoring,studiecoach'),
  ('tutoring', 'en', 'Tutoring & exam prep', 'bijles,huiswerkbegeleiding,examentraining,tutoring,studiecoach'),
  ('tutoring', 'de', 'Nachhilfe & Prüfungsvorbereitung', NULL),
  ('tutoring', 'fr', 'Soutien scolaire & préparation aux examens', NULL),
  ('tutoring', 'es', 'Clases particulares y preparación de exámenes', NULL),
  ('tutoring', 'pt', 'Explicações e preparação para exames', NULL),
  ('business_coach', 'nl', 'Training & coaching', 'coach,training,workshop,loopbaancoach,teamcoaching'),
  ('business_coach', 'en', 'Training & coaching', 'coach,training,workshop,loopbaancoach,teamcoaching'),
  ('business_coach', 'de', 'Training & Coaching', NULL),
  ('business_coach', 'fr', 'Formation & coaching', NULL),
  ('business_coach', 'es', 'Formación y coaching', NULL),
  ('business_coach', 'pt', 'Formação e coaching', NULL),
  ('childcare', 'nl', 'Kinderopvang & peuterspeelzaal', 'kinderopvang,kinderdagverblijf,bso,gastouder,childcare'),
  ('childcare', 'en', 'Childcare & preschool', 'kinderopvang,kinderdagverblijf,bso,gastouder,childcare'),
  ('childcare', 'de', 'Kinderbetreuung & Kita', NULL),
  ('childcare', 'fr', 'Crèche & garde d''enfants', NULL),
  ('childcare', 'es', 'Guardería y educación infantil', NULL),
  ('childcare', 'pt', 'Creche e jardim de infância', NULL),
  ('estate_agent', 'nl', 'Makelaar', 'makelaar,makelaardij,woning verkopen,estate agent,nvm'),
  ('estate_agent', 'en', 'Estate agent', 'makelaar,makelaardij,woning verkopen,estate agent,nvm'),
  ('estate_agent', 'de', 'Immobilienmakler', NULL),
  ('estate_agent', 'fr', 'Agence immobilière', NULL),
  ('estate_agent', 'es', 'Inmobiliaria', NULL),
  ('estate_agent', 'pt', 'Agência imobiliária', NULL),
  ('property_manager', 'nl', 'Vastgoedbeheer', 'vastgoedbeheer,vve beheer,verhuurbeheer,property management'),
  ('property_manager', 'en', 'Property management', 'vastgoedbeheer,vve beheer,verhuurbeheer,property management'),
  ('property_manager', 'de', 'Hausverwaltung', NULL),
  ('property_manager', 'fr', 'Gestion immobilière', NULL),
  ('property_manager', 'es', 'Administración de fincas', NULL),
  ('property_manager', 'pt', 'Gestão de imóveis', NULL),
  ('self_storage', 'nl', 'Opslagruimte', 'opslag,opslagruimte,selfstorage,garagebox,storage'),
  ('self_storage', 'en', 'Self storage', 'opslag,opslagruimte,selfstorage,garagebox,storage'),
  ('self_storage', 'de', 'Selfstorage', NULL),
  ('self_storage', 'fr', 'Self-stockage', NULL),
  ('self_storage', 'es', 'Trasteros', NULL),
  ('self_storage', 'pt', 'Self storage', NULL),
  ('surveyor', 'nl', 'Taxateur', 'taxateur,taxatie,bouwkundige keuring,surveyor,valuation'),
  ('surveyor', 'en', 'Surveyor & valuation', 'taxateur,taxatie,bouwkundige keuring,surveyor,valuation'),
  ('surveyor', 'de', 'Immobiliengutachter', NULL),
  ('surveyor', 'fr', 'Expert immobilier', NULL),
  ('surveyor', 'es', 'Tasador inmobiliario', NULL),
  ('surveyor', 'pt', 'Avaliador imobiliário', NULL),
  ('hotel', 'nl', 'Hotel', 'hotel,overnachten,boutique hotel,stadshotel,accommodatie'),
  ('hotel', 'en', 'Hotel', 'hotel,overnachten,boutique hotel,stadshotel,accommodatie'),
  ('hotel', 'de', 'Hotel', NULL),
  ('hotel', 'fr', 'Hôtel', NULL),
  ('hotel', 'es', 'Hotel', NULL),
  ('hotel', 'pt', 'Hotel', NULL),
  ('bed_breakfast', 'nl', 'B&B & pension', 'bed and breakfast,bnb,pension,logies,guesthouse,vakantiehuis'),
  ('bed_breakfast', 'en', 'B&B & guesthouse', 'bed and breakfast,bnb,pension,logies,guesthouse,vakantiehuis'),
  ('bed_breakfast', 'de', 'B&B & Pension', NULL),
  ('bed_breakfast', 'fr', 'Chambres d''hôtes & pension', NULL),
  ('bed_breakfast', 'es', 'B&B y casa de huéspedes', NULL),
  ('bed_breakfast', 'pt', 'B&B e casa de hóspedes', NULL),
  ('campsite', 'nl', 'Camping & glamping', 'camping,kamperen,glamping,vakantiepark,campsite,chalet'),
  ('campsite', 'en', 'Campsite & glamping', 'camping,kamperen,glamping,vakantiepark,campsite,chalet'),
  ('campsite', 'de', 'Campingplatz & Glamping', NULL),
  ('campsite', 'fr', 'Camping & glamping', NULL),
  ('campsite', 'es', 'Camping y glamping', NULL),
  ('campsite', 'pt', 'Parque de campismo e glamping', NULL),
  ('travel_agency', 'nl', 'Reisbureau', 'reisbureau,reizen,vakantie,reisadvies,travel agency'),
  ('travel_agency', 'en', 'Travel agency', 'reisbureau,reizen,vakantie,reisadvies,travel agency'),
  ('travel_agency', 'de', 'Reisebüro', NULL),
  ('travel_agency', 'fr', 'Agence de voyages', NULL),
  ('travel_agency', 'es', 'Agencia de viajes', NULL),
  ('travel_agency', 'pt', 'Agência de viagens', NULL),
  ('tour_operator', 'nl', 'Excursies & gidsen', 'excursies,rondleiding,stadswandeling,gids,tours,dagtocht'),
  ('tour_operator', 'en', 'Tours & guides', 'excursies,rondleiding,stadswandeling,gids,tours,dagtocht'),
  ('tour_operator', 'de', 'Ausflüge & Reiseführer', NULL),
  ('tour_operator', 'fr', 'Excursions & guides', NULL),
  ('tour_operator', 'es', 'Excursiones y guías', NULL),
  ('tour_operator', 'pt', 'Excursões e guias', NULL),
  ('veterinarian', 'nl', 'Dierenarts', 'dierenarts,dierenkliniek,huisdier,vaccinatie,veterinary'),
  ('veterinarian', 'en', 'Veterinary practice', 'dierenarts,dierenkliniek,huisdier,vaccinatie,veterinary'),
  ('veterinarian', 'de', 'Tierarztpraxis', NULL),
  ('veterinarian', 'fr', 'Cabinet vétérinaire', NULL),
  ('veterinarian', 'es', 'Clínica veterinaria', NULL),
  ('veterinarian', 'pt', 'Clínica veterinária', NULL),
  ('pet_grooming', 'nl', 'Trimsalon', 'trimsalon,hondentrimmer,vachtverzorging,grooming,kattensalon'),
  ('pet_grooming', 'en', 'Pet grooming', 'trimsalon,hondentrimmer,vachtverzorging,grooming,kattensalon'),
  ('pet_grooming', 'de', 'Hundesalon', NULL),
  ('pet_grooming', 'fr', 'Toilettage animalier', NULL),
  ('pet_grooming', 'es', 'Peluquería canina', NULL),
  ('pet_grooming', 'pt', 'Banhos e tosquias', NULL),
  ('dog_training', 'nl', 'Hondentraining & -opvang', 'hondenschool,puppytraining,dierenpension,dog training'),
  ('dog_training', 'en', 'Dog training & daycare', 'hondenschool,puppytraining,dierenpension,dog training'),
  ('dog_training', 'de', 'Hundeschule & Tagesbetreuung', NULL),
  ('dog_training', 'fr', 'Éducation canine & garderie', NULL),
  ('dog_training', 'es', 'Adiestramiento y guardería canina', NULL),
  ('dog_training', 'pt', 'Treino e creche canina', NULL),
  ('equestrian_centre', 'nl', 'Manege & paardensport', 'manege,paardrijden,stal,pension paarden,equestrian,ruitersport'),
  ('equestrian_centre', 'en', 'Stables & equestrian', 'manege,paardrijden,stal,pension paarden,equestrian,ruitersport'),
  ('equestrian_centre', 'de', 'Reitstall & Pferdesport', NULL),
  ('equestrian_centre', 'fr', 'Centre équestre', NULL),
  ('equestrian_centre', 'es', 'Centro ecuestre', NULL),
  ('equestrian_centre', 'pt', 'Centro equestre', NULL),
  ('artisan_maker', 'nl', 'Ambachtsman & maker', 'ambacht,atelier,handgemaakt,keramiek,edelsmid,artisan'),
  ('artisan_maker', 'en', 'Artisan & maker', 'ambacht,atelier,handgemaakt,keramiek,edelsmid,artisan'),
  ('artisan_maker', 'de', 'Handwerk & Manufaktur', NULL),
  ('artisan_maker', 'fr', 'Artisan & créateur', NULL),
  ('artisan_maker', 'es', 'Artesanía y creación', NULL),
  ('artisan_maker', 'pt', 'Artesanato e criação', NULL),
  ('tailor', 'nl', 'Kleermaker & kledingreparatie', 'kleermaker,kledingreparatie,vermaken,naaiatelier,tailor'),
  ('tailor', 'en', 'Tailor & alterations', 'kleermaker,kledingreparatie,vermaken,naaiatelier,tailor'),
  ('tailor', 'de', 'Schneiderei & Änderungen', NULL),
  ('tailor', 'fr', 'Couturier & retouches', NULL),
  ('tailor', 'es', 'Sastrería y arreglos', NULL),
  ('tailor', 'pt', 'Alfaiataria e arranjos', NULL),
  ('dry_cleaner', 'nl', 'Stomerij & wasserij', 'stomerij,wasserij,wassalon,strijkservice,dry cleaning'),
  ('dry_cleaner', 'en', 'Dry cleaning & laundry', 'stomerij,wasserij,wassalon,strijkservice,dry cleaning'),
  ('dry_cleaner', 'de', 'Reinigung & Wäscherei', NULL),
  ('dry_cleaner', 'fr', 'Pressing & blanchisserie', NULL),
  ('dry_cleaner', 'es', 'Tintorería y lavandería', NULL),
  ('dry_cleaner', 'pt', 'Limpeza a seco e lavandaria', NULL),
  ('cleaning_company', 'nl', 'Schoonmaakbedrijf', 'schoonmaakbedrijf,schoonmaak,glazenwasser,cleaning,huishoudelijk'),
  ('cleaning_company', 'en', 'Cleaning company', 'schoonmaakbedrijf,schoonmaak,glazenwasser,cleaning,huishoudelijk'),
  ('cleaning_company', 'de', 'Reinigungsfirma', NULL),
  ('cleaning_company', 'fr', 'Entreprise de nettoyage', NULL),
  ('cleaning_company', 'es', 'Empresa de limpieza', NULL),
  ('cleaning_company', 'pt', 'Empresa de limpeza', NULL),
  ('print_shop', 'nl', 'Drukkerij & signing', 'drukkerij,printshop,belettering,signing,printing,reclameborden'),
  ('print_shop', 'en', 'Printing & signage', 'drukkerij,printshop,belettering,signing,printing,reclameborden'),
  ('print_shop', 'de', 'Druckerei & Werbetechnik', NULL),
  ('print_shop', 'fr', 'Imprimerie & signalétique', NULL),
  ('print_shop', 'es', 'Imprenta y rotulación', NULL),
  ('print_shop', 'pt', 'Gráfica e sinalética', NULL),
  ('funeral_services', 'nl', 'Uitvaartverzorging', 'uitvaart,uitvaartverzorger,begrafenis,crematie,funeral'),
  ('funeral_services', 'en', 'Funeral services', 'uitvaart,uitvaartverzorger,begrafenis,crematie,funeral'),
  ('funeral_services', 'de', 'Bestattungsinstitut', NULL),
  ('funeral_services', 'fr', 'Pompes funèbres', NULL),
  ('funeral_services', 'es', 'Servicios funerarios', NULL),
  ('funeral_services', 'pt', 'Serviços funerários', NULL),
  ('other', 'nl', 'Iets anders', 'anders,overig,other,iets anders'),
  ('other', 'en', 'Something else', 'anders,overig,other,iets anders'),
  ('other', 'de', 'Etwas anderes', NULL),
  ('other', 'fr', 'Autre chose', NULL),
  ('other', 'es', 'Otra cosa', NULL),
  ('other', 'pt', 'Outra coisa', NULL)
ON CONFLICT(industry_key, locale) DO UPDATE SET
  label = excluded.label, search_terms = excluded.search_terms;

-- <<< GENERATED TAXONOMY <<<

-- Reserved labels. Enforced by trg_sites_slug_reserved_ins / _upd in 0006 — without those
-- triggers this table is decoration and `slug = 'www'` inserts cleanly.
--   system    our own product surfaces and anything a support e-mail could be mistaken for
--   protocol  labels that carry mail, DNS, PKI or discovery meaning; handing out `_acme-challenge`
--             or `autodiscover` is a certificate-issuance and credential-phishing hole
--   brand     our own marks plus the brands a European SMB phishing page most often imitates
--   abuse     lures that make a `*.<SITES_ROOT_DOMAIN>` host worth registering in the first place
-- Homoglyph folding and trademark-lookalike (Levenshtein <= 1) rejection run in
-- packages/core/src/slug.ts, which is where a comparison against this list belongs; the table
-- holds exact labels only.
INSERT INTO reserved_slugs (slug, reason, created_at) VALUES
  ('www', 'system', unixepoch() * 1000),
  ('api', 'system', unixepoch() * 1000),
  ('app', 'system', unixepoch() * 1000),
  ('admin', 'system', unixepoch() * 1000),
  ('dashboard', 'system', unixepoch() * 1000),
  ('account', 'system', unixepoch() * 1000),
  ('login', 'system', unixepoch() * 1000),
  ('logout', 'system', unixepoch() * 1000),
  ('signup', 'system', unixepoch() * 1000),
  ('register', 'system', unixepoch() * 1000),
  ('auth', 'system', unixepoch() * 1000),
  ('oauth', 'system', unixepoch() * 1000),
  ('sso', 'system', unixepoch() * 1000),
  ('billing', 'system', unixepoch() * 1000),
  ('checkout', 'system', unixepoch() * 1000),
  ('invoice', 'system', unixepoch() * 1000),
  ('pay', 'system', unixepoch() * 1000),
  ('status', 'system', unixepoch() * 1000),
  ('health', 'system', unixepoch() * 1000),
  ('metrics', 'system', unixepoch() * 1000),
  ('docs', 'system', unixepoch() * 1000),
  ('help', 'system', unixepoch() * 1000),
  ('support', 'system', unixepoch() * 1000),
  ('blog', 'system', unixepoch() * 1000),
  ('news', 'system', unixepoch() * 1000),
  ('about', 'system', unixepoch() * 1000),
  ('legal', 'system', unixepoch() * 1000),
  ('privacy', 'system', unixepoch() * 1000),
  ('terms', 'system', unixepoch() * 1000),
  ('security', 'system', unixepoch() * 1000),
  ('abuse', 'system', unixepoch() * 1000),
  ('postmaster', 'system', unixepoch() * 1000),
  ('hostmaster', 'system', unixepoch() * 1000),
  ('webmaster', 'system', unixepoch() * 1000),
  ('noreply', 'system', unixepoch() * 1000),
  ('no-reply', 'system', unixepoch() * 1000),
  ('root', 'system', unixepoch() * 1000),
  ('test', 'system', unixepoch() * 1000),
  ('staging', 'system', unixepoch() * 1000),
  ('dev', 'system', unixepoch() * 1000),
  ('demo', 'system', unixepoch() * 1000),
  ('sandbox', 'system', unixepoch() * 1000),
  ('internal', 'system', unixepoch() * 1000),
  ('assets', 'system', unixepoch() * 1000),
  ('static', 'system', unixepoch() * 1000),
  ('files', 'system', unixepoch() * 1000),
  ('download', 'system', unixepoch() * 1000),
  ('downloads', 'system', unixepoch() * 1000),
  ('img', 'system', unixepoch() * 1000),
  ('images', 'system', unixepoch() * 1000),
  ('media', 'system', unixepoch() * 1000),
  ('video', 'system', unixepoch() * 1000),
  ('fonts', 'system', unixepoch() * 1000),
  ('js', 'system', unixepoch() * 1000),
  ('css', 'system', unixepoch() * 1000),
  ('search', 'system', unixepoch() * 1000),
  ('sitemap', 'system', unixepoch() * 1000),
  ('robots', 'system', unixepoch() * 1000),
  ('favicon', 'system', unixepoch() * 1000),
  ('manifest', 'system', unixepoch() * 1000),
  ('well-known', 'system', unixepoch() * 1000),
  ('callback', 'system', unixepoch() * 1000),
  ('webhook', 'system', unixepoch() * 1000),
  ('webhooks', 'system', unixepoch() * 1000),
  ('cdn', 'protocol', unixepoch() * 1000),
  ('preview', 'protocol', unixepoch() * 1000),
  ('mail', 'protocol', unixepoch() * 1000),
  ('email', 'protocol', unixepoch() * 1000),
  ('mx', 'protocol', unixepoch() * 1000),
  ('mx1', 'protocol', unixepoch() * 1000),
  ('mx2', 'protocol', unixepoch() * 1000),
  ('imap', 'protocol', unixepoch() * 1000),
  ('pop', 'protocol', unixepoch() * 1000),
  ('pop3', 'protocol', unixepoch() * 1000),
  ('smtp', 'protocol', unixepoch() * 1000),
  ('ftp', 'protocol', unixepoch() * 1000),
  ('sftp', 'protocol', unixepoch() * 1000),
  ('ns', 'protocol', unixepoch() * 1000),
  ('ns1', 'protocol', unixepoch() * 1000),
  ('ns2', 'protocol', unixepoch() * 1000),
  ('ns3', 'protocol', unixepoch() * 1000),
  ('dns', 'protocol', unixepoch() * 1000),
  ('vpn', 'protocol', unixepoch() * 1000),
  ('proxy', 'protocol', unixepoch() * 1000),
  ('autodiscover', 'protocol', unixepoch() * 1000),
  ('autoconfig', 'protocol', unixepoch() * 1000),
  ('wpad', 'protocol', unixepoch() * 1000),
  ('isatap', 'protocol', unixepoch() * 1000),
  ('localhost', 'protocol', unixepoch() * 1000),
  ('local', 'protocol', unixepoch() * 1000),
  ('_acme-challenge', 'protocol', unixepoch() * 1000),
  ('_dmarc', 'protocol', unixepoch() * 1000),
  ('_domainkey', 'protocol', unixepoch() * 1000),
  ('_dnsauth', 'protocol', unixepoch() * 1000),
  ('_psl', 'protocol', unixepoch() * 1000),
  ('cname', 'protocol', unixepoch() * 1000),
  ('edge', 'protocol', unixepoch() * 1000),
  ('origin', 'protocol', unixepoch() * 1000),
  ('gateway', 'protocol', unixepoch() * 1000),
  ('router', 'protocol', unixepoch() * 1000),
  ('server', 'protocol', unixepoch() * 1000),
  ('host', 'protocol', unixepoch() * 1000),
  ('aibuilder', 'brand', unixepoch() * 1000),
  ('mijnsaas', 'brand', unixepoch() * 1000),
  ('cloudflare', 'brand', unixepoch() * 1000),
  ('anthropic', 'brand', unixepoch() * 1000),
  ('claude', 'brand', unixepoch() * 1000),
  ('stripe', 'brand', unixepoch() * 1000),
  ('google', 'brand', unixepoch() * 1000),
  ('apple', 'brand', unixepoch() * 1000),
  ('microsoft', 'brand', unixepoch() * 1000),
  ('amazon', 'brand', unixepoch() * 1000),
  ('meta', 'brand', unixepoch() * 1000),
  ('facebook', 'brand', unixepoch() * 1000),
  ('instagram', 'brand', unixepoch() * 1000),
  ('whatsapp', 'brand', unixepoch() * 1000),
  ('tiktok', 'brand', unixepoch() * 1000),
  ('paypal', 'brand', unixepoch() * 1000),
  ('ideal', 'brand', unixepoch() * 1000),
  ('bancontact', 'brand', unixepoch() * 1000),
  ('ing', 'brand', unixepoch() * 1000),
  ('rabobank', 'brand', unixepoch() * 1000),
  ('abnamro', 'brand', unixepoch() * 1000),
  ('knab', 'brand', unixepoch() * 1000),
  ('belastingdienst', 'brand', unixepoch() * 1000),
  ('kvk', 'brand', unixepoch() * 1000),
  ('digid', 'brand', unixepoch() * 1000),
  ('postnl', 'brand', unixepoch() * 1000),
  ('bol', 'brand', unixepoch() * 1000),
  ('marktplaats', 'brand', unixepoch() * 1000),
  ('thuisbezorgd', 'brand', unixepoch() * 1000),
  ('phish', 'abuse', unixepoch() * 1000),
  ('phishing', 'abuse', unixepoch() * 1000),
  ('verify', 'abuse', unixepoch() * 1000),
  ('verification', 'abuse', unixepoch() * 1000),
  ('secure', 'abuse', unixepoch() * 1000),
  ('confirm', 'abuse', unixepoch() * 1000),
  ('update-account', 'abuse', unixepoch() * 1000),
  ('wallet', 'abuse', unixepoch() * 1000),
  ('crypto', 'abuse', unixepoch() * 1000),
  ('bitcoin', 'abuse', unixepoch() * 1000),
  ('airdrop', 'abuse', unixepoch() * 1000),
  ('giveaway', 'abuse', unixepoch() * 1000),
  ('casino', 'abuse', unixepoch() * 1000),
  ('porn', 'abuse', unixepoch() * 1000),
  ('xxx', 'abuse', unixepoch() * 1000),
  ('escort', 'abuse', unixepoch() * 1000),
  ('pharmacy-online', 'abuse', unixepoch() * 1000),
  ('cheap-pills', 'abuse', unixepoch() * 1000)
ON CONFLICT(slug) DO NOTHING;
