/**
 * GENERATED by scripts/media-library/emit-catalogue.mjs — do not edit by hand.
 *
 * Empty until the first ingest runs. An empty catalogue is a VALID state, not a broken one:
 * `selectHeroVideo` returns `null`, and a `null` hero video means the header is a full-screen
 * poster rather than a moving one. Nothing downstream branches on the library being populated.
 */

import type { MediaLibrary } from './types';

export const MEDIA_LIBRARY: MediaLibrary = {
  version: 1,
  builtAt: '',
  videos: [],
  images: [],
} as const;
