import { UnknownIndustryError } from './errors';
import type { Locale } from './locales';

/**
 * The curated industry taxonomy: 14 groups, 104 leaves.
 *
 * This table mirrors `industry_groups` / `industries` / `industry_translations` in the control
 * plane, and it is load-bearing in four different places, which is why it is data and not a switch
 * statement:
 *
 *   1. **The onboarding combobox.** `GET /v1/bootstrap` returns `{key, groupKey, label,
 *      searchTerms, icon}` straight from here. `searchTerms` carries Dutch *and* English aliases because a Dutch
 *      user types `kapper` and an expat types `hairdresser`, and neither should get zero results.
 *   2. **The JSON-LD `@type`.** `schemaOrgType` is a real `LocalBusiness` subtype, verified
 *      against schema.org and never invented. Architecture §7.12: an invented type (`DJService`) silently
 *      disables every rich result on the page, so a DJ is a `ProfessionalService`. `SchemaOrgType`
 *      is a closed union, which makes "this industry's type is in the allowlist" a *compile-time*
 *      guarantee rather than a test.
 *   3. **`additionalType`.** Where no subtype is apt, the type falls back and the specific meaning
 *      is carried by a Wikidata or schema.org URI instead of a fabricated `@type`.
 *   4. **The design DNA.** `dnaId` picks one of the four Phase 1 archetypes. The full 20-preset
 *      registry from the design dimension lands in Phase 2; each of those presets maps onto one of
 *      these four (`espresso-warm`, `gold-heritage`, `market-fresh` and `paper-craft` all reduce to
 *      `warm_trattoria`, `hi-vis-utility` and `steel-industrial` to `garage_steel`, and so on), so
 *      Phase 2 refines this column instead of rewriting it.
 *
 * Display order is array order; the D1 `sort_order` of a row is its index × 10.
 */

/**
 * The closed icon set.
 *
 * Names, not glyphs: the marketing island and the dashboard render these through their own sprite,
 * and a closed union means adding an industry cannot introduce an icon nobody drew.
 */
export const INDUSTRY_ICONS = [
  'utensils',
  'coffee',
  'bread',
  'beer',
  'ice-cream',
  'scissors',
  'sparkles',
  'stethoscope',
  'tooth',
  'eye',
  'pill',
  'dumbbell',
  'lotus',
  'music',
  'wrench',
  'plug',
  'hard-hat',
  'hammer',
  'paint-roller',
  'key',
  'leaf',
  'sun',
  'car',
  'bike',
  'shopping-bag',
  'shirt',
  'gem',
  'flower',
  'book',
  'sofa',
  'cpu',
  'paw',
  'calculator',
  'scale',
  'briefcase',
  'camera',
  'graduation-cap',
  'baby',
  'bed',
  'plane',
  'building',
  'palette',
  'heart',
  'box',
] as const;

/** One icon from the closed set. */
export type IndustryIcon = (typeof INDUSTRY_ICONS)[number];

/**
 * The four design-DNA archetypes shipped in Phase 1.
 *
 * Mirrors `DNA_IDS` in `@aibuilder/site-schema`'s model-facing schema. It is duplicated rather than
 * imported because `site-schema` depends on nothing (architecture §2) and this package must not
 * become the reason that changes; the two lists are four literals long and are asserted equal by
 * the generator's contract test.
 */
export const PHASE1_DNA_IDS = [
  'midnight_neon',
  'warm_trattoria',
  'clinical_trust',
  'garage_steel',
] as const;

/** A Phase 1 design-DNA archetype. */
export type DnaId = (typeof PHASE1_DNA_IDS)[number];

/**
 * The compiled `LocalBusiness` subtype allowlist.
 *
 * Every entry is a real schema.org type that is `LocalBusiness` or one of its descendants. This is
 * the enum the model-facing `SiteStructureGen.jsonLd.schemaOrgType` is built from, and the list the
 * JSON-LD emitter validates against at emit time (architecture §7.12).
 *
 * Notable corrections against the design dimensions, each verified against schema.org:
 *   - `TireStore`, not `TireShop` — the latter does not exist.
 *   - `EducationalOrganization` is **not** under `LocalBusiness`; language and music schools are
 *     `ProfessionalService` with an `additionalType` of `https://schema.org/School`.
 *   - `Attorney` (a `LegalService` subtype) is preferred over bare `LegalService` for lawyers.
 */
export const SCHEMA_ORG_TYPES = [
  'AccountingService',
  'ArtGallery',
  'Attorney',
  'AutoBodyShop',
  'AutoDealer',
  'AutoRepair',
  'AutoWash',
  'AutomotiveBusiness',
  'Bakery',
  'BarOrPub',
  'BeautySalon',
  'BedAndBreakfast',
  'BikeStore',
  'BookStore',
  'Brewery',
  'CafeOrCoffeeShop',
  'Campground',
  'ChildCare',
  'ClothingStore',
  'DaySpa',
  'Dentist',
  'DryCleaningOrLaundry',
  'Electrician',
  'ElectronicsStore',
  'EmploymentAgency',
  'ExerciseGym',
  'FastFoodRestaurant',
  'FinancialService',
  'Florist',
  'FoodEstablishment',
  'FurnitureStore',
  'GeneralContractor',
  'GroceryStore',
  'HVACBusiness',
  'HairSalon',
  'HealthAndBeautyBusiness',
  'HomeAndConstructionBusiness',
  'Hotel',
  'HousePainter',
  'IceCreamShop',
  'InsuranceAgency',
  'JewelryStore',
  'LocalBusiness',
  'Locksmith',
  'MedicalBusiness',
  'NailSalon',
  'NightClub',
  'Notary',
  'Optician',
  'PetStore',
  'Pharmacy',
  'Physician',
  'Physiotherapy',
  'Plumber',
  'ProfessionalService',
  'RealEstateAgent',
  'Restaurant',
  'RoofingContractor',
  'SelfStorage',
  'ShoeStore',
  'SportingGoodsStore',
  'SportsActivityLocation',
  'SportsClub',
  'Store',
  'TattooParlor',
  'TennisComplex',
  'TireStore',
  'ToyStore',
  'TravelAgency',
  'VeterinaryCare',
] as const;

/** A `LocalBusiness` subtype from the allowlist. */
export type SchemaOrgType = (typeof SCHEMA_ORG_TYPES)[number];

/** The 14 top-level groups, in display order. */
export const INDUSTRY_GROUP_KEYS = [
  'food_drink',
  'beauty',
  'health',
  'sport',
  'trades',
  'automotive',
  'retail',
  'professional',
  'events',
  'education',
  'real_estate',
  'travel',
  'pets',
  'crafts',
] as const;

/** A top-level group key. */
export type IndustryGroupKey = (typeof INDUSTRY_GROUP_KEYS)[number];

/** A label in every supported locale. Totality is enforced by `Record<Locale, string>`. */
export type LocalisedLabels = Readonly<Record<Locale, string>>;

/** One top-level group of the taxonomy. */
export interface IndustryGroup {
  readonly key: IndustryGroupKey;
  readonly labels: LocalisedLabels;
  readonly icon: IndustryIcon;
}

/** One leaf industry. */
export interface Industry {
  /** Stable key. Written to `sites.industry_key`; never renamed, because it is a join key. */
  readonly key: string;
  readonly groupKey: IndustryGroupKey;
  readonly labels: LocalisedLabels;
  /**
   * Dutch and English aliases for the combobox, lowercase.
   *
   * These are *search* terms, not synonyms shown to the user: misspellings, regional words and the
   * English name all belong here, because the cost of a missing alias is a user who cannot find
   * their own trade in the list and abandons onboarding at step one.
   */
  readonly searchTerms: readonly string[];
  readonly icon: IndustryIcon;
  /** Validated `LocalBusiness` subtype for the JSON-LD `@graph`. */
  readonly schemaOrgType: SchemaOrgType;
  /**
   * A Wikidata or schema.org URI carrying the meaning `schemaOrgType` had to drop, or `null`.
   *
   * Emitted as `additionalType`. This is the honest alternative to inventing a `@type`: the graph
   * stays valid, rich results keep working, and the specific trade is still stated.
   */
  readonly additionalType: string | null;
  readonly dnaId: DnaId;
}

/** The 14 groups, in display order. */
export const INDUSTRY_GROUPS: readonly IndustryGroup[] = [
  {
    key: 'food_drink',
    icon: 'utensils',
    labels: {
      nl: 'Eten & drinken',
      en: 'Food & drink',
      de: 'Essen & Trinken',
      fr: 'Restauration',
      es: 'Comida y bebida',
      pt: 'Comida e bebida',
    },
  },
  {
    key: 'beauty',
    icon: 'scissors',
    labels: {
      nl: 'Schoonheid & verzorging',
      en: 'Beauty & personal care',
      de: 'Beauty & Pflege',
      fr: 'Beauté & soins',
      es: 'Belleza y cuidado personal',
      pt: 'Beleza e cuidados pessoais',
    },
  },
  {
    key: 'health',
    icon: 'stethoscope',
    labels: {
      nl: 'Gezondheid & zorg',
      en: 'Health & medical',
      de: 'Gesundheit & Medizin',
      fr: 'Santé & médical',
      es: 'Salud y medicina',
      pt: 'Saúde e medicina',
    },
  },
  {
    key: 'sport',
    icon: 'dumbbell',
    labels: {
      nl: 'Sport & fitness',
      en: 'Sport & fitness',
      de: 'Sport & Fitness',
      fr: 'Sport & fitness',
      es: 'Deporte y fitness',
      pt: 'Desporto e fitness',
    },
  },
  {
    key: 'trades',
    icon: 'wrench',
    labels: {
      nl: 'Bouw & installatie',
      en: 'Home & trades',
      de: 'Bau & Handwerk',
      fr: 'Bâtiment & artisanat',
      es: 'Construcción y oficios',
      pt: 'Construção e ofícios',
    },
  },
  {
    key: 'automotive',
    icon: 'car',
    labels: {
      nl: 'Auto & vervoer',
      en: 'Automotive & transport',
      de: 'Auto & Verkehr',
      fr: 'Auto & transport',
      es: 'Automoción y transporte',
      pt: 'Automóvel e transporte',
    },
  },
  {
    key: 'retail',
    icon: 'shopping-bag',
    labels: {
      nl: 'Winkels',
      en: 'Retail',
      de: 'Einzelhandel',
      fr: 'Commerce de détail',
      es: 'Comercio',
      pt: 'Comércio',
    },
  },
  {
    key: 'professional',
    icon: 'briefcase',
    labels: {
      nl: 'Zakelijke diensten',
      en: 'Professional services',
      de: 'Dienstleistungen',
      fr: 'Services professionnels',
      es: 'Servicios profesionales',
      pt: 'Serviços profissionais',
    },
  },
  {
    key: 'events',
    icon: 'music',
    labels: {
      nl: 'Events & entertainment',
      en: 'Events & entertainment',
      de: 'Events & Entertainment',
      fr: 'Événements & spectacle',
      es: 'Eventos y entretenimiento',
      pt: 'Eventos e entretenimento',
    },
  },
  {
    key: 'education',
    icon: 'graduation-cap',
    labels: {
      nl: 'Onderwijs',
      en: 'Education & training',
      de: 'Bildung & Weiterbildung',
      fr: 'Éducation & formation',
      es: 'Educación y formación',
      pt: 'Educação e formação',
    },
  },
  {
    key: 'real_estate',
    icon: 'building',
    labels: {
      nl: 'Vastgoed',
      en: 'Real estate',
      de: 'Immobilien',
      fr: 'Immobilier',
      es: 'Inmobiliaria',
      pt: 'Imobiliário',
    },
  },
  {
    key: 'travel',
    icon: 'bed',
    labels: {
      nl: 'Reizen & verblijf',
      en: 'Travel & hospitality',
      de: 'Reisen & Übernachten',
      fr: 'Voyage & hébergement',
      es: 'Viajes y alojamiento',
      pt: 'Viagens e alojamento',
    },
  },
  {
    key: 'pets',
    icon: 'paw',
    labels: {
      nl: 'Huisdieren',
      en: 'Pets & animals',
      de: 'Haustiere',
      fr: 'Animaux',
      es: 'Mascotas',
      pt: 'Animais',
    },
  },
  {
    key: 'crafts',
    icon: 'hammer',
    labels: {
      nl: 'Ambacht & overig',
      en: 'Craft, services & other',
      de: 'Handwerk & Sonstiges',
      fr: 'Artisanat & autres',
      es: 'Artesanía y otros',
      pt: 'Artesanato e outros',
    },
  },
];

/**
 * The 104 leaf industries, grouped and in display order.
 *
 * Written out in full rather than generated: every row carries four independent editorial decisions
 * (six labels, the search aliases, the schema.org type and the design DNA) and none of them follow
 * from the key.
 */
export const INDUSTRIES: readonly Industry[] = [
  /* ── G1 · Eten & drinken ──────────────────────────────────────────────────────────────────── */
  {
    key: 'restaurant',
    groupKey: 'food_drink',
    icon: 'utensils',
    schemaOrgType: 'Restaurant',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Restaurant',
      en: 'Restaurant',
      de: 'Restaurant',
      fr: 'Restaurant',
      es: 'Restaurante',
      pt: 'Restaurante',
    },
    searchTerms: ['restaurant', 'eetcafe', 'bistro', 'brasserie', 'eethuis', 'dining', 'eatery'],
  },
  {
    key: 'cafe',
    groupKey: 'food_drink',
    icon: 'coffee',
    schemaOrgType: 'CafeOrCoffeeShop',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Café & lunchroom',
      en: 'Café & lunchroom',
      de: 'Café & Bistro',
      fr: 'Café & salon de thé',
      es: 'Cafetería',
      pt: 'Café & casa de chá',
    },
    searchTerms: ['cafe', 'koffie', 'lunchroom', 'koffiebar', 'espressobar', 'coffee', 'brunch'],
  },
  {
    key: 'bakery',
    groupKey: 'food_drink',
    icon: 'bread',
    schemaOrgType: 'Bakery',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Bakkerij & patisserie',
      en: 'Bakery & patisserie',
      de: 'Bäckerei & Konditorei',
      fr: 'Boulangerie & pâtisserie',
      es: 'Panadería y pastelería',
      pt: 'Padaria e pastelaria',
    },
    searchTerms: ['bakker', 'bakkerij', 'brood', 'banketbakker', 'taart', 'bakery', 'pastry'],
  },
  {
    key: 'bar_pub',
    groupKey: 'food_drink',
    icon: 'beer',
    schemaOrgType: 'BarOrPub',
    additionalType: null,
    dnaId: 'midnight_neon',
    labels: {
      nl: 'Bar & café',
      en: 'Bar & pub',
      de: 'Bar & Kneipe',
      fr: 'Bar & pub',
      es: 'Bar y pub',
      pt: 'Bar e pub',
    },
    searchTerms: ['bar', 'kroeg', 'cafe', 'pub', 'bruin cafe', 'borrel', 'cocktailbar'],
  },
  {
    key: 'takeaway',
    groupKey: 'food_drink',
    icon: 'utensils',
    schemaOrgType: 'FastFoodRestaurant',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Afhaal & fastfood',
      en: 'Takeaway & fast food',
      de: 'Imbiss & Lieferdienst',
      fr: 'Vente à emporter & fast-food',
      es: 'Comida para llevar',
      pt: 'Comida para levar',
    },
    searchTerms: ['afhaal', 'snackbar', 'cafetaria', 'pizzeria', 'shoarma', 'takeaway', 'friture'],
  },
  {
    key: 'food_truck',
    groupKey: 'food_drink',
    icon: 'utensils',
    schemaOrgType: 'FoodEstablishment',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Foodtruck',
      en: 'Food truck',
      de: 'Foodtruck',
      fr: 'Food truck',
      es: 'Food truck',
      pt: 'Food truck',
    },
    searchTerms: ['foodtruck', 'street food', 'marktkraam', 'mobiele keuken', 'food truck'],
  },
  {
    key: 'ice_cream',
    groupKey: 'food_drink',
    icon: 'ice-cream',
    schemaOrgType: 'IceCreamShop',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'IJssalon',
      en: 'Ice cream parlour',
      de: 'Eisdiele',
      fr: 'Glacier',
      es: 'Heladería',
      pt: 'Gelataria',
    },
    searchTerms: ['ijssalon', 'ijs', 'gelato', 'ijsboerderij', 'ice cream', 'sorbet'],
  },
  {
    key: 'catering',
    groupKey: 'food_drink',
    icon: 'utensils',
    schemaOrgType: 'FoodEstablishment',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Catering',
      en: 'Catering',
      de: 'Catering',
      fr: 'Traiteur',
      es: 'Catering',
      pt: 'Catering',
    },
    searchTerms: ['catering', 'partyservice', 'traiteur', 'bedrijfscatering', 'buffet'],
  },
  {
    key: 'brewery',
    groupKey: 'food_drink',
    icon: 'beer',
    schemaOrgType: 'Brewery',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Brouwerij & distilleerderij',
      en: 'Brewery & distillery',
      de: 'Brauerei & Destillerie',
      fr: 'Brasserie & distillerie',
      es: 'Cervecería artesanal y destilería',
      pt: 'Cervejaria e destilaria',
    },
    searchTerms: ['brouwerij', 'bier', 'distilleerderij', 'stokerij', 'brewery', 'craft beer'],
  },

  /* ── G2 · Schoonheid & verzorging ─────────────────────────────────────────────────────────── */
  {
    key: 'hairdresser',
    groupKey: 'beauty',
    icon: 'scissors',
    schemaOrgType: 'HairSalon',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Kapsalon',
      en: 'Hair salon',
      de: 'Friseursalon',
      fr: 'Salon de coiffure',
      es: 'Peluquería',
      pt: 'Cabeleireiro',
    },
    searchTerms: ['kapper', 'kapsalon', 'haarstylist', 'coiffure', 'hairdresser', 'hair salon'],
  },
  {
    key: 'barbershop',
    groupKey: 'beauty',
    icon: 'scissors',
    schemaOrgType: 'HairSalon',
    additionalType: null,
    dnaId: 'midnight_neon',
    labels: {
      nl: 'Barbershop',
      en: 'Barbershop',
      de: 'Barbershop',
      fr: 'Barbier',
      es: 'Barbería',
      pt: 'Barbearia',
    },
    searchTerms: ['barbier', 'barbershop', 'herenkapper', 'baard', 'scheren', 'barber'],
  },
  {
    key: 'beauty_salon',
    groupKey: 'beauty',
    icon: 'sparkles',
    schemaOrgType: 'BeautySalon',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Schoonheidssalon',
      en: 'Beauty salon',
      de: 'Kosmetikstudio',
      fr: 'Institut de beauté',
      es: 'Salón de belleza',
      pt: 'Salão de beleza',
    },
    searchTerms: ['schoonheidsspecialist', 'beauty', 'huidverzorging', 'gezichtsbehandeling'],
  },
  {
    key: 'nail_studio',
    groupKey: 'beauty',
    icon: 'sparkles',
    schemaOrgType: 'NailSalon',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Nagelstudio',
      en: 'Nail studio',
      de: 'Nagelstudio',
      fr: 'Onglerie',
      es: 'Salón de uñas',
      pt: 'Estúdio de unhas',
    },
    searchTerms: ['nagelstudio', 'nagels', 'manicure', 'pedicure', 'gellak', 'nail studio'],
  },
  {
    key: 'day_spa',
    groupKey: 'beauty',
    icon: 'lotus',
    schemaOrgType: 'DaySpa',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Wellness & sauna',
      en: 'Spa & sauna',
      de: 'Wellness & Sauna',
      fr: 'Spa & sauna',
      es: 'Spa y sauna',
      pt: 'Spa e sauna',
    },
    searchTerms: ['wellness', 'spa', 'sauna', 'beautyfarm', 'hammam', 'day spa'],
  },
  {
    key: 'massage',
    groupKey: 'beauty',
    icon: 'lotus',
    schemaOrgType: 'HealthAndBeautyBusiness',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Massagepraktijk',
      en: 'Massage therapy',
      de: 'Massagepraxis',
      fr: 'Cabinet de massage',
      es: 'Centro de masajes',
      pt: 'Massagem terapêutica',
    },
    searchTerms: ['massage', 'masseur', 'sportmassage', 'ontspanningsmassage', 'shiatsu'],
  },
  {
    key: 'tattoo_studio',
    groupKey: 'beauty',
    icon: 'palette',
    schemaOrgType: 'TattooParlor',
    additionalType: null,
    dnaId: 'midnight_neon',
    labels: {
      nl: 'Tattoo & piercing',
      en: 'Tattoo & piercing',
      de: 'Tattoo & Piercing',
      fr: 'Tatouage & piercing',
      es: 'Tatuajes y piercings',
      pt: 'Tatuagens e piercings',
    },
    searchTerms: ['tattoo', 'tatoeage', 'piercing', 'tattooshop', 'inkt', 'tattoo studio'],
  },

  /* ── G3 · Gezondheid & zorg ───────────────────────────────────────────────────────────────── */
  {
    key: 'gp_practice',
    groupKey: 'health',
    icon: 'stethoscope',
    schemaOrgType: 'Physician',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Huisartsenpraktijk',
      en: 'GP practice',
      de: 'Hausarztpraxis',
      fr: 'Cabinet de médecine générale',
      es: 'Consulta de medicina general',
      pt: 'Clínica de medicina geral',
    },
    searchTerms: ['huisarts', 'dokter', 'huisartsenpraktijk', 'medisch centrum', 'gp', 'doctor'],
  },
  {
    key: 'dentist',
    groupKey: 'health',
    icon: 'tooth',
    schemaOrgType: 'Dentist',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Tandartspraktijk',
      en: 'Dental practice',
      de: 'Zahnarztpraxis',
      fr: 'Cabinet dentaire',
      es: 'Clínica dental',
      pt: 'Clínica dentária',
    },
    searchTerms: ['tandarts', 'mondhygienist', 'orthodontist', 'gebit', 'dentist', 'dental'],
  },
  {
    key: 'physiotherapist',
    groupKey: 'health',
    icon: 'heart',
    schemaOrgType: 'Physiotherapy',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Fysiotherapie',
      en: 'Physiotherapy',
      de: 'Physiotherapie',
      fr: 'Kinésithérapie',
      es: 'Fisioterapia',
      pt: 'Fisioterapia',
    },
    searchTerms: ['fysio', 'fysiotherapie', 'manueel therapeut', 'revalidatie', 'physio'],
  },
  {
    key: 'chiropractor',
    groupKey: 'health',
    icon: 'stethoscope',
    schemaOrgType: 'MedicalBusiness',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Chiropractor & osteopaat',
      en: 'Chiropractor & osteopath',
      de: 'Chiropraktik & Osteopathie',
      fr: 'Chiropracteur & ostéopathe',
      es: 'Quiropráctico y osteópata',
      pt: 'Quiroprático e osteopata',
    },
    searchTerms: ['chiropractor', 'osteopaat', 'rug', 'nek', 'chiropractic', 'osteopath'],
  },
  {
    key: 'psychologist',
    groupKey: 'health',
    icon: 'heart',
    schemaOrgType: 'MedicalBusiness',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Psycholoog & therapie',
      en: 'Psychologist & therapy',
      de: 'Psychologe & Therapie',
      fr: 'Psychologue & thérapie',
      es: 'Psicólogo y terapia',
      pt: 'Psicólogo e terapia',
    },
    searchTerms: ['psycholoog', 'therapeut', 'ggz', 'coaching', 'psychologist', 'therapy'],
  },
  {
    key: 'optician',
    groupKey: 'health',
    icon: 'eye',
    schemaOrgType: 'Optician',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Opticien',
      en: 'Optician',
      de: 'Optiker',
      fr: 'Opticien',
      es: 'Óptica',
      pt: 'Ótica',
    },
    searchTerms: ['opticien', 'brillen', 'oogmeting', 'contactlenzen', 'optician', 'glasses'],
  },
  {
    key: 'pharmacy',
    groupKey: 'health',
    icon: 'pill',
    schemaOrgType: 'Pharmacy',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Apotheek',
      en: 'Pharmacy',
      de: 'Apotheke',
      fr: 'Pharmacie',
      es: 'Farmacia',
      pt: 'Farmácia',
    },
    searchTerms: ['apotheek', 'drogist', 'medicijnen', 'recept', 'pharmacy', 'chemist'],
  },
  {
    key: 'home_care',
    groupKey: 'health',
    icon: 'stethoscope',
    schemaOrgType: 'MedicalBusiness',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Thuiszorg',
      en: 'Home care',
      de: 'Häusliche Pflege',
      fr: 'Aide à domicile',
      es: 'Ayuda a domicilio',
      pt: 'Apoio domiciliário',
    },
    searchTerms: ['thuiszorg', 'verpleging', 'mantelzorg', 'wijkverpleging', 'home care'],
  },

  /* ── G4 · Sport & fitness ─────────────────────────────────────────────────────────────────── */
  {
    key: 'gym',
    groupKey: 'sport',
    icon: 'dumbbell',
    schemaOrgType: 'ExerciseGym',
    additionalType: null,
    dnaId: 'midnight_neon',
    labels: {
      nl: 'Sportschool',
      en: 'Gym & fitness',
      de: 'Fitnessstudio',
      fr: 'Salle de sport',
      es: 'Gimnasio',
      pt: 'Ginásio',
    },
    searchTerms: ['sportschool', 'fitness', 'gym', 'krachttraining', 'health club'],
  },
  {
    key: 'crossfit_box',
    groupKey: 'sport',
    icon: 'dumbbell',
    schemaOrgType: 'ExerciseGym',
    additionalType: null,
    dnaId: 'midnight_neon',
    labels: {
      nl: 'CrossFit & functional',
      en: 'CrossFit & functional',
      de: 'CrossFit & Functional',
      fr: 'CrossFit & training fonctionnel',
      es: 'CrossFit y entrenamiento funcional',
      pt: 'CrossFit e treino funcional',
    },
    searchTerms: ['crossfit', 'box', 'bootcamp', 'functional training', 'hyrox'],
  },
  {
    key: 'yoga_studio',
    groupKey: 'sport',
    icon: 'lotus',
    schemaOrgType: 'SportsActivityLocation',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Yoga & pilates',
      en: 'Yoga & pilates',
      de: 'Yoga & Pilates',
      fr: 'Yoga & pilates',
      es: 'Yoga y pilates',
      pt: 'Ioga e pilates',
    },
    searchTerms: ['yoga', 'pilates', 'yogastudio', 'meditatie', 'ashtanga', 'vinyasa'],
  },
  {
    key: 'personal_trainer',
    groupKey: 'sport',
    icon: 'dumbbell',
    schemaOrgType: 'SportsActivityLocation',
    additionalType: null,
    dnaId: 'midnight_neon',
    labels: {
      nl: 'Personal trainer',
      en: 'Personal trainer',
      de: 'Personal Trainer',
      fr: 'Coach sportif',
      es: 'Entrenador personal',
      pt: 'Personal trainer',
    },
    searchTerms: ['personal trainer', 'pt', 'leefstijlcoach', 'voedingsadvies', 'coach'],
  },
  {
    key: 'martial_arts',
    groupKey: 'sport',
    icon: 'dumbbell',
    schemaOrgType: 'SportsClub',
    additionalType: null,
    dnaId: 'midnight_neon',
    labels: {
      nl: 'Vechtsport & boksen',
      en: 'Martial arts & boxing',
      de: 'Kampfsport & Boxen',
      fr: 'Arts martiaux & boxe',
      es: 'Artes marciales y boxeo',
      pt: 'Artes marciais e boxe',
    },
    searchTerms: ['vechtsport', 'boksen', 'kickboksen', 'judo', 'karate', 'bjj', 'mma'],
  },
  {
    key: 'dance_school',
    groupKey: 'sport',
    icon: 'music',
    schemaOrgType: 'SportsActivityLocation',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Dansschool',
      en: 'Dance school',
      de: 'Tanzschule',
      fr: 'École de danse',
      es: 'Escuela de baile',
      pt: 'Escola de dança',
    },
    searchTerms: ['dansschool', 'dansen', 'ballet', 'salsa', 'streetdance', 'dance'],
  },
  {
    key: 'racket_club',
    groupKey: 'sport',
    icon: 'dumbbell',
    schemaOrgType: 'TennisComplex',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Tennis, padel & golf',
      en: 'Tennis, padel & golf',
      de: 'Tennis, Padel & Golf',
      fr: 'Tennis, padel & golf',
      es: 'Tenis, pádel y golf',
      pt: 'Ténis, padel e golfe',
    },
    searchTerms: ['tennis', 'padel', 'golf', 'squash', 'racketclub', 'tennisbaan'],
  },

  /* ── G5 · Bouw & installatie ──────────────────────────────────────────────────────────────── */
  {
    key: 'plumber',
    groupKey: 'trades',
    icon: 'wrench',
    schemaOrgType: 'Plumber',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Loodgieter',
      en: 'Plumber',
      de: 'Klempner',
      fr: 'Plombier',
      es: 'Fontanería',
      pt: 'Canalizador',
    },
    searchTerms: ['loodgieter', 'sanitair', 'lekkage', 'riool', 'plumber', 'badkamer'],
  },
  {
    key: 'electrician',
    groupKey: 'trades',
    icon: 'plug',
    schemaOrgType: 'Electrician',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Elektricien',
      en: 'Electrician',
      de: 'Elektriker',
      fr: 'Électricien',
      es: 'Electricista',
      pt: 'Eletricista',
    },
    searchTerms: ['elektricien', 'installateur', 'groepenkast', 'laadpaal', 'electrician'],
  },
  {
    key: 'hvac_heatpump',
    groupKey: 'trades',
    icon: 'wrench',
    schemaOrgType: 'HVACBusiness',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Cv, koeling & warmtepompen',
      en: 'Heating, cooling & heat pumps',
      de: 'Heizung, Kühlung & Wärmepumpen',
      fr: 'Chauffage, climatisation & pompes à chaleur',
      es: 'Calefacción, climatización y bombas de calor',
      pt: 'Aquecimento, climatização e bombas de calor',
    },
    searchTerms: ['cv ketel', 'warmtepomp', 'airco', 'verwarming', 'koeling', 'hvac'],
  },
  {
    key: 'general_contractor',
    groupKey: 'trades',
    icon: 'hard-hat',
    schemaOrgType: 'GeneralContractor',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Aannemer',
      en: 'Builder & contractor',
      de: 'Bauunternehmen',
      fr: 'Entreprise de construction',
      es: 'Empresa constructora',
      pt: 'Empresa de construção',
    },
    searchTerms: ['aannemer', 'bouwbedrijf', 'verbouwing', 'metselaar', 'contractor', 'builder'],
  },
  {
    key: 'painter_decorator',
    groupKey: 'trades',
    icon: 'paint-roller',
    schemaOrgType: 'HousePainter',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Schilder & stukadoor',
      en: 'Painter & decorator',
      de: 'Maler & Stuckateur',
      fr: 'Peintre & plâtrier',
      es: 'Pintor y yesero',
      pt: 'Pintor e estucador',
    },
    searchTerms: ['schilder', 'schilderwerk', 'stukadoor', 'behanger', 'painter', 'decorator'],
  },
  {
    key: 'roofer',
    groupKey: 'trades',
    icon: 'hard-hat',
    schemaOrgType: 'RoofingContractor',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Dakdekker',
      en: 'Roofer',
      de: 'Dachdecker',
      fr: 'Couvreur',
      es: 'Tejados y cubiertas',
      pt: 'Coberturas e telhados',
    },
    searchTerms: ['dakdekker', 'dak', 'dakbedekking', 'dakgoot', 'roofer', 'lekkend dak'],
  },
  {
    key: 'carpenter',
    groupKey: 'trades',
    icon: 'hammer',
    schemaOrgType: 'HomeAndConstructionBusiness',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Timmerman & meubelmaker',
      en: 'Carpenter & joinery',
      de: 'Tischlerei & Schreinerei',
      fr: 'Menuiserie & ébénisterie',
      es: 'Carpintería y ebanistería',
      pt: 'Carpintaria e marcenaria',
    },
    searchTerms: ['timmerman', 'meubelmaker', 'kozijnen', 'interieurbouw', 'carpenter'],
  },
  {
    key: 'locksmith',
    groupKey: 'trades',
    icon: 'key',
    schemaOrgType: 'Locksmith',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Slotenmaker',
      en: 'Locksmith',
      de: 'Schlüsseldienst',
      fr: 'Serrurier',
      es: 'Cerrajería',
      pt: 'Serralharia',
    },
    searchTerms: ['slotenmaker', 'sloten', 'buitengesloten', 'inbraakbeveiliging', 'locksmith'],
  },
  {
    key: 'landscaper',
    groupKey: 'trades',
    icon: 'leaf',
    schemaOrgType: 'HomeAndConstructionBusiness',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Hovenier & tuinaanleg',
      en: 'Gardener & landscaping',
      de: 'Garten- & Landschaftsbau',
      fr: 'Paysagiste & jardinier',
      es: 'Jardinería y paisajismo',
      pt: 'Jardinagem e paisagismo',
    },
    searchTerms: ['hovenier', 'tuinman', 'tuinaanleg', 'bestrating', 'gardener', 'landscaping'],
  },
  {
    key: 'solar_installer',
    groupKey: 'trades',
    icon: 'sun',
    schemaOrgType: 'HomeAndConstructionBusiness',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Zonnepanelen & energie',
      en: 'Solar & energy',
      de: 'Solaranlagen & Energie',
      fr: 'Panneaux solaires & énergie',
      es: 'Placas solares y energía',
      pt: 'Painéis solares e energia',
    },
    searchTerms: ['zonnepanelen', 'solar', 'thuisbatterij', 'isolatie', 'energieadvies'],
  },

  /* ── G6 · Auto & vervoer ──────────────────────────────────────────────────────────────────── */
  {
    key: 'car_repair',
    groupKey: 'automotive',
    icon: 'wrench',
    schemaOrgType: 'AutoRepair',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Autogarage',
      en: 'Garage & repair',
      de: 'Autowerkstatt',
      fr: 'Garage automobile',
      es: 'Taller mecánico',
      pt: 'Oficina automóvel',
    },
    searchTerms: ['garage', 'automonteur', 'apk', 'onderhoud', 'car repair', 'werkplaats'],
  },
  {
    key: 'car_dealer',
    groupKey: 'automotive',
    icon: 'car',
    schemaOrgType: 'AutoDealer',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Autodealer',
      en: 'Car dealer',
      de: 'Autohaus',
      fr: 'Concessionnaire automobile',
      es: 'Concesionario',
      pt: 'Stand automóvel',
    },
    searchTerms: ['autodealer', 'occasions', 'autobedrijf', 'showroom', 'car dealer'],
  },
  {
    key: 'car_bodywork',
    groupKey: 'automotive',
    icon: 'car',
    schemaOrgType: 'AutoBodyShop',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Autoschadeherstel',
      en: 'Bodywork & paint',
      de: 'Karosserie & Lack',
      fr: 'Carrosserie & peinture',
      es: 'Chapa y pintura',
      pt: 'Chapa e pintura',
    },
    searchTerms: ['autoschade', 'plaatwerk', 'spuiterij', 'deuk', 'bodyshop', 'ruitschade'],
  },
  {
    key: 'tyre_service',
    groupKey: 'automotive',
    icon: 'car',
    schemaOrgType: 'TireStore',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Bandenservice',
      en: 'Tyres & wheels',
      de: 'Reifenservice',
      fr: 'Pneus & jantes',
      es: 'Neumáticos y llantas',
      pt: 'Pneus e jantes',
    },
    searchTerms: ['banden', 'bandenservice', 'velgen', 'winterbanden', 'tyres', 'uitlijnen'],
  },
  {
    key: 'car_wash',
    groupKey: 'automotive',
    icon: 'car',
    schemaOrgType: 'AutoWash',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Carwash & detailing',
      en: 'Car wash & detailing',
      de: 'Autowäsche & Aufbereitung',
      fr: 'Lavage auto & detailing',
      es: 'Lavado de coches y detailing',
      pt: 'Lavagem auto e detailing',
    },
    searchTerms: ['carwash', 'autowasserette', 'poetsen', 'detailing', 'coating', 'car wash'],
  },
  {
    key: 'bike_shop',
    groupKey: 'automotive',
    icon: 'bike',
    schemaOrgType: 'BikeStore',
    additionalType: null,
    dnaId: 'garage_steel',
    labels: {
      nl: 'Fietsenwinkel & reparatie',
      en: 'Bicycle shop & repair',
      de: 'Fahrradladen & Werkstatt',
      fr: 'Magasin & réparation de vélos',
      es: 'Tienda y taller de bicicletas',
      pt: 'Loja e oficina de bicicletas',
    },
    searchTerms: ['fietsenmaker', 'fietsenwinkel', 'ebike', 'fietsreparatie', 'bike shop'],
  },
  {
    key: 'driving_school',
    groupKey: 'automotive',
    icon: 'car',
    schemaOrgType: 'AutomotiveBusiness',
    additionalType: 'https://www.wikidata.org/wiki/Q2143665',
    dnaId: 'midnight_neon',
    labels: {
      nl: 'Rijschool',
      en: 'Driving school',
      de: 'Fahrschule',
      fr: 'Auto-école',
      es: 'Autoescuela',
      pt: 'Escola de condução',
    },
    searchTerms: ['rijschool', 'rijles', 'rijbewijs', 'motorrijschool', 'driving school'],
  },

  /* ── G7 · Winkels ─────────────────────────────────────────────────────────────────────────── */
  {
    key: 'clothing_store',
    groupKey: 'retail',
    icon: 'shirt',
    schemaOrgType: 'ClothingStore',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Kleding & mode',
      en: 'Clothing & fashion',
      de: 'Mode & Bekleidung',
      fr: 'Vêtements & mode',
      es: 'Ropa y moda',
      pt: 'Roupa e moda',
    },
    searchTerms: ['kledingwinkel', 'mode', 'boetiek', 'damesmode', 'herenmode', 'fashion'],
  },
  {
    key: 'shoe_store',
    groupKey: 'retail',
    icon: 'shopping-bag',
    schemaOrgType: 'ShoeStore',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Schoenen & lederwaren',
      en: 'Shoes & leather',
      de: 'Schuhe & Lederwaren',
      fr: 'Chaussures & maroquinerie',
      es: 'Calzado y marroquinería',
      pt: 'Calçado e marroquinaria',
    },
    searchTerms: ['schoenenwinkel', 'schoenen', 'tassen', 'lederwaren', 'shoes', 'sneakers'],
  },
  {
    key: 'jeweller',
    groupKey: 'retail',
    icon: 'gem',
    schemaOrgType: 'JewelryStore',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Juwelier & horloges',
      en: 'Jewellery & watches',
      de: 'Juwelier & Uhren',
      fr: 'Bijouterie & horlogerie',
      es: 'Joyería y relojería',
      pt: 'Joalharia e relojoaria',
    },
    searchTerms: ['juwelier', 'sieraden', 'horloges', 'goudsmid', 'trouwringen', 'jewellery'],
  },
  {
    key: 'florist',
    groupKey: 'retail',
    icon: 'flower',
    schemaOrgType: 'Florist',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Bloemist',
      en: 'Florist',
      de: 'Blumenladen',
      fr: 'Fleuriste',
      es: 'Floristería',
      pt: 'Florista',
    },
    searchTerms: ['bloemist', 'bloemen', 'boeket', 'bloemenwinkel', 'florist', 'rouwbloemen'],
  },
  {
    key: 'bookshop',
    groupKey: 'retail',
    icon: 'book',
    schemaOrgType: 'BookStore',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Boekhandel & kantoorartikelen',
      en: 'Bookshop & stationery',
      de: 'Buchhandlung & Schreibwaren',
      fr: 'Librairie & papeterie',
      es: 'Librería y papelería',
      pt: 'Livraria e papelaria',
    },
    searchTerms: ['boekhandel', 'boeken', 'kantoorboekhandel', 'tijdschriften', 'bookshop'],
  },
  {
    key: 'toy_store',
    groupKey: 'retail',
    icon: 'shopping-bag',
    schemaOrgType: 'ToyStore',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Speelgoed & baby',
      en: 'Toys & baby',
      de: 'Spielwaren & Baby',
      fr: 'Jouets & puériculture',
      es: 'Juguetes y bebé',
      pt: 'Brinquedos e bebé',
    },
    searchTerms: ['speelgoedwinkel', 'speelgoed', 'babyspullen', 'kinderwagen', 'toys'],
  },
  {
    key: 'furniture_store',
    groupKey: 'retail',
    icon: 'sofa',
    schemaOrgType: 'FurnitureStore',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Meubels & wonen',
      en: 'Furniture & interior',
      de: 'Möbel & Wohnen',
      fr: 'Meubles & décoration',
      es: 'Muebles y decoración',
      pt: 'Móveis e decoração',
    },
    searchTerms: ['meubelwinkel', 'meubels', 'woonwinkel', 'interieur', 'furniture', 'bankstel'],
  },
  {
    key: 'electronics_store',
    groupKey: 'retail',
    icon: 'cpu',
    schemaOrgType: 'ElectronicsStore',
    additionalType: null,
    dnaId: 'midnight_neon',
    labels: {
      nl: 'Elektronica & telefoons',
      en: 'Electronics & phones',
      de: 'Elektronik & Handys',
      fr: 'Électronique & téléphonie',
      es: 'Electrónica y telefonía',
      pt: 'Eletrónica e telemóveis',
    },
    searchTerms: ['elektronica', 'telefoonwinkel', 'computerwinkel', 'reparatie', 'electronics'],
  },
  {
    key: 'sports_store',
    groupKey: 'retail',
    icon: 'dumbbell',
    schemaOrgType: 'SportingGoodsStore',
    additionalType: null,
    dnaId: 'midnight_neon',
    labels: {
      nl: 'Sport & outdoor',
      en: 'Sports & outdoor',
      de: 'Sport & Outdoor',
      fr: 'Sport & plein air',
      es: 'Deporte y aire libre',
      pt: 'Desporto e ar livre',
    },
    searchTerms: ['sportwinkel', 'sportzaak', 'outdoor', 'hardloopwinkel', 'sports store'],
  },
  {
    key: 'pet_store',
    groupKey: 'retail',
    icon: 'paw',
    schemaOrgType: 'PetStore',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Dierenwinkel',
      en: 'Pet shop',
      de: 'Zoofachhandel',
      fr: 'Animalerie',
      es: 'Tienda de mascotas',
      pt: 'Loja de animais',
    },
    searchTerms: ['dierenwinkel', 'dierenspeciaalzaak', 'diervoeding', 'aquarium', 'pet shop'],
  },
  {
    key: 'butcher',
    groupKey: 'retail',
    icon: 'shopping-bag',
    schemaOrgType: 'Store',
    additionalType: 'https://www.wikidata.org/wiki/Q329737',
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Slagerij',
      en: 'Butcher',
      de: 'Metzgerei',
      fr: 'Boucherie',
      es: 'Carnicería',
      pt: 'Talho',
    },
    searchTerms: ['slager', 'slagerij', 'vlees', 'worst', 'barbecue', 'butcher', 'poelier'],
  },
  {
    key: 'farm_shop',
    groupKey: 'retail',
    icon: 'leaf',
    schemaOrgType: 'GroceryStore',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Groentewinkel & boerderijwinkel',
      en: 'Greengrocer & farm shop',
      de: 'Gemüseladen & Hofladen',
      fr: 'Primeur & magasin de ferme',
      es: 'Frutería y tienda de granja',
      pt: 'Frutaria e loja da quinta',
    },
    searchTerms: ['groenteboer', 'boerderijwinkel', 'streekproducten', 'markt', 'farm shop'],
  },

  /* ── G8 · Zakelijke diensten ──────────────────────────────────────────────────────────────── */
  {
    key: 'accountant',
    groupKey: 'professional',
    icon: 'calculator',
    schemaOrgType: 'AccountingService',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Accountant & boekhouder',
      en: 'Accountant & bookkeeper',
      de: 'Buchhaltung & Rechnungswesen',
      fr: 'Expert-comptable',
      es: 'Asesoría contable',
      pt: 'Contabilidade',
    },
    searchTerms: ['accountant', 'boekhouder', 'administratiekantoor', 'jaarrekening', 'btw'],
  },
  {
    key: 'lawyer',
    groupKey: 'professional',
    icon: 'scale',
    schemaOrgType: 'Attorney',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Advocaat',
      en: 'Lawyer',
      de: 'Rechtsanwalt',
      fr: 'Avocat',
      es: 'Abogado',
      pt: 'Advogado',
    },
    searchTerms: ['advocaat', 'advocatenkantoor', 'juridisch advies', 'lawyer', 'mediation'],
  },
  {
    key: 'notary',
    groupKey: 'professional',
    icon: 'scale',
    schemaOrgType: 'Notary',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Notaris',
      en: 'Notary',
      de: 'Notar',
      fr: 'Notaire',
      es: 'Notaría',
      pt: 'Notário',
    },
    searchTerms: ['notaris', 'notariskantoor', 'testament', 'akte', 'notary', 'hypotheekakte'],
  },
  {
    key: 'tax_adviser',
    groupKey: 'professional',
    icon: 'calculator',
    schemaOrgType: 'AccountingService',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Belastingadviseur',
      en: 'Tax adviser',
      de: 'Steuerberater',
      fr: 'Conseiller fiscal',
      es: 'Asesor fiscal',
      pt: 'Consultor fiscal',
    },
    searchTerms: ['belastingadviseur', 'belastingaangifte', 'fiscalist', 'tax adviser'],
  },
  {
    key: 'insurance_broker',
    groupKey: 'professional',
    icon: 'briefcase',
    schemaOrgType: 'InsuranceAgency',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Verzekeringsadviseur',
      en: 'Insurance broker',
      de: 'Versicherungsmakler',
      fr: 'Courtier en assurances',
      es: 'Corredor de seguros',
      pt: 'Corretor de seguros',
    },
    searchTerms: ['verzekeringen', 'assurantiekantoor', 'tussenpersoon', 'insurance broker'],
  },
  {
    key: 'mortgage_adviser',
    groupKey: 'professional',
    icon: 'calculator',
    schemaOrgType: 'FinancialService',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Hypotheek- & financieel advies',
      en: 'Mortgage & financial advice',
      de: 'Baufinanzierung & Finanzberatung',
      fr: 'Courtier en crédit & conseil financier',
      es: 'Asesoría hipotecaria y financiera',
      pt: 'Crédito habitação e consultoria financeira',
    },
    searchTerms: ['hypotheekadviseur', 'hypotheek', 'financieel advies', 'mortgage adviser'],
  },
  {
    key: 'consultant',
    groupKey: 'professional',
    icon: 'briefcase',
    schemaOrgType: 'ProfessionalService',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Adviesbureau',
      en: 'Consultant',
      de: 'Unternehmensberatung',
      fr: 'Cabinet de conseil',
      es: 'Consultoría',
      pt: 'Consultoria',
    },
    searchTerms: ['adviesbureau', 'consultant', 'interim', 'bedrijfsadvies', 'consultancy'],
  },
  {
    key: 'marketing_agency',
    groupKey: 'professional',
    icon: 'briefcase',
    schemaOrgType: 'ProfessionalService',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Marketing- & reclamebureau',
      en: 'Marketing & advertising',
      de: 'Marketing- & Werbeagentur',
      fr: 'Agence de marketing & publicité',
      es: 'Agencia de marketing y publicidad',
      pt: 'Agência de marketing e publicidade',
    },
    searchTerms: ['marketingbureau', 'reclamebureau', 'seo', 'social media', 'marketing'],
  },
  {
    key: 'it_services',
    groupKey: 'professional',
    icon: 'cpu',
    schemaOrgType: 'ProfessionalService',
    additionalType: null,
    dnaId: 'midnight_neon',
    labels: {
      nl: 'IT-diensten & webdesign',
      en: 'IT services & web',
      de: 'IT-Dienstleistungen & Web',
      fr: 'Services informatiques & web',
      es: 'Servicios informáticos y web',
      pt: 'Serviços de TI e web',
    },
    searchTerms: ['ict', 'it beheer', 'webdesign', 'softwarebedrijf', 'systeembeheer', 'it'],
  },
  {
    key: 'recruitment_agency',
    groupKey: 'professional',
    icon: 'briefcase',
    schemaOrgType: 'EmploymentAgency',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Werving & uitzendbureau',
      en: 'Recruitment & staffing',
      de: 'Personalvermittlung & Zeitarbeit',
      fr: 'Recrutement & intérim',
      es: 'Selección y trabajo temporal',
      pt: 'Recrutamento e trabalho temporário',
    },
    searchTerms: ['uitzendbureau', 'recruitment', 'werving en selectie', 'detachering'],
  },
  {
    key: 'architect',
    groupKey: 'professional',
    icon: 'building',
    schemaOrgType: 'ProfessionalService',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Architect & ingenieursbureau',
      en: 'Architect & engineering',
      de: 'Architektur- & Ingenieurbüro',
      fr: "Architecte & bureau d'études",
      es: 'Arquitectura e ingeniería',
      pt: 'Arquitetura e engenharia',
    },
    searchTerms: ['architect', 'architectenbureau', 'bouwkundig', 'ingenieursbureau'],
  },

  /* ── G9 · Events & entertainment ──────────────────────────────────────────────────────────── */
  {
    key: 'dj',
    groupKey: 'events',
    icon: 'music',
    schemaOrgType: 'ProfessionalService',
    additionalType: 'https://www.wikidata.org/wiki/Q130857',
    dnaId: 'midnight_neon',
    labels: { nl: 'DJ', en: 'DJ', de: 'DJ', fr: 'DJ', es: 'DJ', pt: 'DJ' },
    searchTerms: ['dj', 'discjockey', 'drive-in show', 'bruiloft dj', 'feest dj'],
  },
  {
    key: 'live_band',
    groupKey: 'events',
    icon: 'music',
    schemaOrgType: 'ProfessionalService',
    additionalType: 'https://schema.org/MusicGroup',
    dnaId: 'midnight_neon',
    labels: {
      nl: 'Band & muzikant',
      en: 'Band & musician',
      de: 'Band & Musiker',
      fr: 'Groupe & musicien',
      es: 'Grupo y músico',
      pt: 'Banda e músico',
    },
    searchTerms: ['band', 'muzikant', 'coverband', 'live muziek', 'zanger', 'musician'],
  },
  {
    key: 'wedding_planner',
    groupKey: 'events',
    icon: 'sparkles',
    schemaOrgType: 'ProfessionalService',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Bruiloft- & eventplanner',
      en: 'Wedding & event planner',
      de: 'Hochzeits- & Eventplanung',
      fr: "Organisation de mariages & d'événements",
      es: 'Organización de bodas y eventos',
      pt: 'Organização de casamentos e eventos',
    },
    searchTerms: ['weddingplanner', 'bruiloft', 'trouwen', 'eventbureau', 'ceremoniemeester'],
  },
  {
    key: 'photographer',
    groupKey: 'events',
    icon: 'camera',
    schemaOrgType: 'ProfessionalService',
    additionalType: 'https://www.wikidata.org/wiki/Q33231',
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Fotograaf',
      en: 'Photographer',
      de: 'Fotograf',
      fr: 'Photographe',
      es: 'Fotógrafo',
      pt: 'Fotógrafo',
    },
    searchTerms: ['fotograaf', 'fotostudio', 'bruidsfotograaf', 'portret', 'photographer'],
  },
  {
    key: 'videographer',
    groupKey: 'events',
    icon: 'camera',
    schemaOrgType: 'ProfessionalService',
    additionalType: 'https://www.wikidata.org/wiki/Q1027872',
    dnaId: 'midnight_neon',
    labels: {
      nl: 'Videograaf',
      en: 'Videographer',
      de: 'Videograf',
      fr: 'Vidéaste',
      es: 'Videógrafo',
      pt: 'Videógrafo',
    },
    searchTerms: ['videograaf', 'videoproductie', 'bedrijfsfilm', 'drone', 'videographer'],
  },
  {
    key: 'nightclub',
    groupKey: 'events',
    icon: 'music',
    schemaOrgType: 'NightClub',
    additionalType: null,
    dnaId: 'midnight_neon',
    labels: {
      nl: 'Nachtclub',
      en: 'Nightclub',
      de: 'Nachtclub',
      fr: 'Boîte de nuit',
      es: 'Discoteca',
      pt: 'Discoteca',
    },
    searchTerms: ['nachtclub', 'discotheek', 'club', 'uitgaan', 'nightclub', 'dansen'],
  },
  {
    key: 'party_rental',
    groupKey: 'events',
    icon: 'sparkles',
    schemaOrgType: 'LocalBusiness',
    additionalType: 'https://www.wikidata.org/wiki/Q1092268',
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Feest- & materiaalverhuur',
      en: 'Party & equipment rental',
      de: 'Party- & Geräteverleih',
      fr: 'Location de matériel de fête',
      es: 'Alquiler para fiestas y eventos',
      pt: 'Aluguer de material para festas',
    },
    searchTerms: ['partyverhuur', 'verhuur', 'springkussen', 'tentverhuur', 'party rental'],
  },
  {
    key: 'art_gallery',
    groupKey: 'events',
    icon: 'palette',
    schemaOrgType: 'ArtGallery',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Kunstgalerie',
      en: 'Art gallery',
      de: 'Kunstgalerie',
      fr: "Galerie d'art",
      es: 'Galería de arte',
      pt: 'Galeria de arte',
    },
    searchTerms: ['galerie', 'kunst', 'expositie', 'atelier', 'art gallery', 'lijstenmaker'],
  },

  /* ── G10 · Onderwijs ──────────────────────────────────────────────────────────────────────── */
  {
    key: 'language_school',
    groupKey: 'education',
    icon: 'graduation-cap',
    schemaOrgType: 'ProfessionalService',
    additionalType: 'https://schema.org/School',
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Talenschool',
      en: 'Language school',
      de: 'Sprachschule',
      fr: 'École de langues',
      es: 'Escuela de idiomas',
      pt: 'Escola de línguas',
    },
    searchTerms: ['taalschool', 'talenschool', 'nt2', 'inburgering', 'language school'],
  },
  {
    key: 'music_school',
    groupKey: 'education',
    icon: 'music',
    schemaOrgType: 'ProfessionalService',
    additionalType: 'https://schema.org/School',
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Muziekschool',
      en: 'Music school',
      de: 'Musikschule',
      fr: 'École de musique',
      es: 'Escuela de música',
      pt: 'Escola de música',
    },
    searchTerms: ['muziekschool', 'muziekles', 'gitaarles', 'pianoles', 'zangles'],
  },
  {
    key: 'tutoring',
    groupKey: 'education',
    icon: 'graduation-cap',
    schemaOrgType: 'ProfessionalService',
    additionalType: 'https://schema.org/EducationalOrganization',
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Bijles & examentraining',
      en: 'Tutoring & exam prep',
      de: 'Nachhilfe & Prüfungsvorbereitung',
      fr: 'Soutien scolaire & préparation aux examens',
      es: 'Clases particulares y preparación de exámenes',
      pt: 'Explicações e preparação para exames',
    },
    searchTerms: ['bijles', 'huiswerkbegeleiding', 'examentraining', 'tutoring', 'studiecoach'],
  },
  {
    key: 'business_coach',
    groupKey: 'education',
    icon: 'graduation-cap',
    schemaOrgType: 'ProfessionalService',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Training & coaching',
      en: 'Training & coaching',
      de: 'Training & Coaching',
      fr: 'Formation & coaching',
      es: 'Formación y coaching',
      pt: 'Formação e coaching',
    },
    searchTerms: ['coach', 'training', 'workshop', 'loopbaancoach', 'teamcoaching'],
  },
  {
    key: 'childcare',
    groupKey: 'education',
    icon: 'baby',
    schemaOrgType: 'ChildCare',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Kinderopvang & peuterspeelzaal',
      en: 'Childcare & preschool',
      de: 'Kinderbetreuung & Kita',
      fr: "Crèche & garde d'enfants",
      es: 'Guardería y educación infantil',
      pt: 'Creche e jardim de infância',
    },
    searchTerms: ['kinderopvang', 'kinderdagverblijf', 'bso', 'gastouder', 'childcare'],
  },

  /* ── G11 · Vastgoed ───────────────────────────────────────────────────────────────────────── */
  {
    key: 'estate_agent',
    groupKey: 'real_estate',
    icon: 'building',
    schemaOrgType: 'RealEstateAgent',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Makelaar',
      en: 'Estate agent',
      de: 'Immobilienmakler',
      fr: 'Agence immobilière',
      es: 'Inmobiliaria',
      pt: 'Agência imobiliária',
    },
    searchTerms: ['makelaar', 'makelaardij', 'woning verkopen', 'estate agent', 'nvm'],
  },
  {
    key: 'property_manager',
    groupKey: 'real_estate',
    icon: 'building',
    schemaOrgType: 'RealEstateAgent',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Vastgoedbeheer',
      en: 'Property management',
      de: 'Hausverwaltung',
      fr: 'Gestion immobilière',
      es: 'Administración de fincas',
      pt: 'Gestão de imóveis',
    },
    searchTerms: ['vastgoedbeheer', 'vve beheer', 'verhuurbeheer', 'property management'],
  },
  {
    key: 'self_storage',
    groupKey: 'real_estate',
    icon: 'box',
    schemaOrgType: 'SelfStorage',
    additionalType: null,
    dnaId: 'midnight_neon',
    labels: {
      nl: 'Opslagruimte',
      en: 'Self storage',
      de: 'Selfstorage',
      fr: 'Self-stockage',
      es: 'Trasteros',
      pt: 'Self storage',
    },
    searchTerms: ['opslag', 'opslagruimte', 'selfstorage', 'garagebox', 'storage'],
  },
  {
    key: 'surveyor',
    groupKey: 'real_estate',
    icon: 'building',
    schemaOrgType: 'ProfessionalService',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Taxateur',
      en: 'Surveyor & valuation',
      de: 'Immobiliengutachter',
      fr: 'Expert immobilier',
      es: 'Tasador inmobiliario',
      pt: 'Avaliador imobiliário',
    },
    searchTerms: ['taxateur', 'taxatie', 'bouwkundige keuring', 'surveyor', 'valuation'],
  },

  /* ── G12 · Reizen & verblijf ──────────────────────────────────────────────────────────────── */
  {
    key: 'hotel',
    groupKey: 'travel',
    icon: 'bed',
    schemaOrgType: 'Hotel',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: { nl: 'Hotel', en: 'Hotel', de: 'Hotel', fr: 'Hôtel', es: 'Hotel', pt: 'Hotel' },
    searchTerms: ['hotel', 'overnachten', 'boutique hotel', 'stadshotel', 'accommodatie'],
  },
  {
    key: 'bed_breakfast',
    groupKey: 'travel',
    icon: 'bed',
    schemaOrgType: 'BedAndBreakfast',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'B&B & pension',
      en: 'B&B & guesthouse',
      de: 'B&B & Pension',
      fr: "Chambres d'hôtes & pension",
      es: 'B&B y casa de huéspedes',
      pt: 'B&B e casa de hóspedes',
    },
    searchTerms: ['bed and breakfast', 'bnb', 'pension', 'logies', 'guesthouse', 'vakantiehuis'],
  },
  {
    key: 'campsite',
    groupKey: 'travel',
    icon: 'leaf',
    schemaOrgType: 'Campground',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Camping & glamping',
      en: 'Campsite & glamping',
      de: 'Campingplatz & Glamping',
      fr: 'Camping & glamping',
      es: 'Camping y glamping',
      pt: 'Parque de campismo e glamping',
    },
    searchTerms: ['camping', 'kamperen', 'glamping', 'vakantiepark', 'campsite', 'chalet'],
  },
  {
    key: 'travel_agency',
    groupKey: 'travel',
    icon: 'plane',
    schemaOrgType: 'TravelAgency',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Reisbureau',
      en: 'Travel agency',
      de: 'Reisebüro',
      fr: 'Agence de voyages',
      es: 'Agencia de viajes',
      pt: 'Agência de viagens',
    },
    searchTerms: ['reisbureau', 'reizen', 'vakantie', 'reisadvies', 'travel agency'],
  },
  {
    key: 'tour_operator',
    groupKey: 'travel',
    icon: 'plane',
    schemaOrgType: 'TravelAgency',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Excursies & gidsen',
      en: 'Tours & guides',
      de: 'Ausflüge & Reiseführer',
      fr: 'Excursions & guides',
      es: 'Excursiones y guías',
      pt: 'Excursões e guias',
    },
    searchTerms: ['excursies', 'rondleiding', 'stadswandeling', 'gids', 'tours', 'dagtocht'],
  },

  /* ── G13 · Huisdieren ─────────────────────────────────────────────────────────────────────── */
  {
    key: 'veterinarian',
    groupKey: 'pets',
    icon: 'paw',
    schemaOrgType: 'VeterinaryCare',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Dierenarts',
      en: 'Veterinary practice',
      de: 'Tierarztpraxis',
      fr: 'Cabinet vétérinaire',
      es: 'Clínica veterinaria',
      pt: 'Clínica veterinária',
    },
    searchTerms: ['dierenarts', 'dierenkliniek', 'huisdier', 'vaccinatie', 'veterinary'],
  },
  {
    key: 'pet_grooming',
    groupKey: 'pets',
    icon: 'paw',
    schemaOrgType: 'LocalBusiness',
    additionalType: 'https://www.wikidata.org/wiki/Q3355098',
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Trimsalon',
      en: 'Pet grooming',
      de: 'Hundesalon',
      fr: 'Toilettage animalier',
      es: 'Peluquería canina',
      pt: 'Banhos e tosquias',
    },
    searchTerms: ['trimsalon', 'hondentrimmer', 'vachtverzorging', 'grooming', 'kattensalon'],
  },
  {
    key: 'dog_training',
    groupKey: 'pets',
    icon: 'paw',
    schemaOrgType: 'LocalBusiness',
    additionalType: 'https://www.wikidata.org/wiki/Q1194479',
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Hondentraining & -opvang',
      en: 'Dog training & daycare',
      de: 'Hundeschule & Tagesbetreuung',
      fr: 'Éducation canine & garderie',
      es: 'Adiestramiento y guardería canina',
      pt: 'Treino e creche canina',
    },
    searchTerms: ['hondenschool', 'puppytraining', 'dierenpension', 'dog training'],
  },
  {
    key: 'equestrian_centre',
    groupKey: 'pets',
    icon: 'paw',
    schemaOrgType: 'SportsActivityLocation',
    additionalType: null,
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Manege & paardensport',
      en: 'Stables & equestrian',
      de: 'Reitstall & Pferdesport',
      fr: 'Centre équestre',
      es: 'Centro ecuestre',
      pt: 'Centro equestre',
    },
    searchTerms: ['manege', 'paardrijden', 'stal', 'pension paarden', 'equestrian', 'ruitersport'],
  },

  /* ── G14 · Ambacht & overig ───────────────────────────────────────────────────────────────── */
  {
    key: 'artisan_maker',
    groupKey: 'crafts',
    icon: 'hammer',
    schemaOrgType: 'LocalBusiness',
    additionalType: 'https://www.wikidata.org/wiki/Q1294787',
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Ambachtsman & maker',
      en: 'Artisan & maker',
      de: 'Handwerk & Manufaktur',
      fr: 'Artisan & créateur',
      es: 'Artesanía y creación',
      pt: 'Artesanato e criação',
    },
    searchTerms: ['ambacht', 'atelier', 'handgemaakt', 'keramiek', 'edelsmid', 'artisan'],
  },
  {
    key: 'tailor',
    groupKey: 'crafts',
    icon: 'scissors',
    schemaOrgType: 'ClothingStore',
    additionalType: 'https://www.wikidata.org/wiki/Q874405',
    dnaId: 'warm_trattoria',
    labels: {
      nl: 'Kleermaker & kledingreparatie',
      en: 'Tailor & alterations',
      de: 'Schneiderei & Änderungen',
      fr: 'Couturier & retouches',
      es: 'Sastrería y arreglos',
      pt: 'Alfaiataria e arranjos',
    },
    searchTerms: ['kleermaker', 'kledingreparatie', 'vermaken', 'naaiatelier', 'tailor'],
  },
  {
    key: 'dry_cleaner',
    groupKey: 'crafts',
    icon: 'sparkles',
    schemaOrgType: 'DryCleaningOrLaundry',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Stomerij & wasserij',
      en: 'Dry cleaning & laundry',
      de: 'Reinigung & Wäscherei',
      fr: 'Pressing & blanchisserie',
      es: 'Tintorería y lavandería',
      pt: 'Limpeza a seco e lavandaria',
    },
    searchTerms: ['stomerij', 'wasserij', 'wassalon', 'strijkservice', 'dry cleaning'],
  },
  {
    key: 'cleaning_company',
    groupKey: 'crafts',
    icon: 'sparkles',
    schemaOrgType: 'ProfessionalService',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Schoonmaakbedrijf',
      en: 'Cleaning company',
      de: 'Reinigungsfirma',
      fr: 'Entreprise de nettoyage',
      es: 'Empresa de limpieza',
      pt: 'Empresa de limpeza',
    },
    searchTerms: ['schoonmaakbedrijf', 'schoonmaak', 'glazenwasser', 'cleaning', 'huishoudelijk'],
  },
  {
    key: 'print_shop',
    groupKey: 'crafts',
    icon: 'book',
    schemaOrgType: 'ProfessionalService',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Drukkerij & signing',
      en: 'Printing & signage',
      de: 'Druckerei & Werbetechnik',
      fr: 'Imprimerie & signalétique',
      es: 'Imprenta y rotulación',
      pt: 'Gráfica e sinalética',
    },
    searchTerms: ['drukkerij', 'printshop', 'belettering', 'signing', 'printing', 'reclameborden'],
  },
  {
    key: 'funeral_services',
    groupKey: 'crafts',
    icon: 'heart',
    schemaOrgType: 'LocalBusiness',
    additionalType: 'https://www.wikidata.org/wiki/Q1195942',
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Uitvaartverzorging',
      en: 'Funeral services',
      de: 'Bestattungsinstitut',
      fr: 'Pompes funèbres',
      es: 'Servicios funerarios',
      pt: 'Serviços funerários',
    },
    searchTerms: ['uitvaart', 'uitvaartverzorger', 'begrafenis', 'crematie', 'funeral'],
  },
  {
    key: 'other',
    groupKey: 'crafts',
    icon: 'shopping-bag',
    schemaOrgType: 'LocalBusiness',
    additionalType: null,
    dnaId: 'clinical_trust',
    labels: {
      nl: 'Iets anders',
      en: 'Something else',
      de: 'Etwas anderes',
      fr: 'Autre chose',
      es: 'Otra cosa',
      pt: 'Outra coisa',
    },
    searchTerms: ['anders', 'overig', 'other', 'iets anders'],
  },
];

/** Index built once at module load; the combobox and the submit path both hit it per request. */
const INDUSTRY_BY_KEY: ReadonlyMap<string, Industry> = new Map(
  INDUSTRIES.map((industry) => [industry.key, industry]),
);

/** Index of groups by key. */
const GROUP_BY_KEY: ReadonlyMap<string, IndustryGroup> = new Map(
  INDUSTRY_GROUPS.map((group) => [group.key, group]),
);

/**
 * Looks up an industry by key, or `null`.
 *
 * Returns `null` rather than throwing because the caller is usually validating untrusted input (an
 * `industryKey` off the wire); use `assertIndustry()` where a missing row means our own data is
 * inconsistent.
 */
export function industryByKey(key: string): Industry | null {
  return INDUSTRY_BY_KEY.get(key) ?? null;
}

/** Looks up a group by key, or `null`. */
export function industryGroupByKey(key: string): IndustryGroup | null {
  return GROUP_BY_KEY.get(key) ?? null;
}

/** Every industry in one group, in display order. */
export function industriesByGroup(groupKey: IndustryGroupKey): readonly Industry[] {
  return INDUSTRIES.filter((industry) => industry.groupKey === groupKey);
}

/**
 * The D1 `sort_order` for an industry, or `null` when the key is unknown.
 *
 * Derived from array position (index × 10) so display order lives in exactly one place and the seed
 * migration cannot drift from the UI.
 */
export function industrySortOrder(key: string): number | null {
  const index = INDUSTRIES.findIndex((industry) => industry.key === key);
  return index === -1 ? null : index * 10;
}

/** Narrows an untrusted string to a value in the schema.org allowlist. */
export function isSchemaOrgType(value: unknown): value is SchemaOrgType {
  return typeof value === 'string' && (SCHEMA_ORG_TYPES as readonly string[]).includes(value);
}

/**
 * Looks up an industry by key or throws.
 *
 * For paths where a missing row means *our* data is inconsistent — a `sites.industry_key` read back
 * from D1, a taxonomy key inside a stored `SiteDoc` — rather than a bad request.
 */
export function assertIndustry(key: string): Industry {
  const industry = industryByKey(key);
  if (industry === null) throw new UnknownIndustryError(key);
  return industry;
}
